/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzasystem.ui;
import com.sun.glass.events.KeyEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import pizzasystem.data.OtherProductType;
import pizzasystem.data.PizzaTaste;
import pizzasystem.data.PizzaTaste.Size;
import pizzasystem.Main;
import pizzasystem.data.ClientRequest;
import pizzasystem.data.ClientRequest.Status;
import pizzasystem.data.Employee;
import pizzasystem.data.Employee.Role;
import pizzasystem.data.Person;
import pizzasystem.data.Pizza;
import pizzasystem.utility.PasswordHasher;

/**
 *
 * @author jools
 */
public class MainFrame extends javax.swing.JFrame {
    
    private ClientRequest currentRequest;


    public static String[] getTasteList() {
        ArrayList<String> tastes = new ArrayList<>();
        try {
            for (PizzaTaste pizza : Main.getPizzaria().getMenu().getPizzaTastes()){
                tastes.add(pizza.getName());
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return tastes.toArray(new String[tastes.size()]);
    }

    public static String[] getDrinkList() {
        ArrayList<String> drinks = new ArrayList<>();
        try {
            for (OtherProductType drink : Main.getPizzaria().getMenu().getOtherProductTypes()){
                drinks.add(drink.getName());
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return drinks.toArray(new String[drinks.size()]);
    }

    /**
     * Creates new form MainFrame
     */
     // para diferentes usuarios quando voltar a tela

    Timer timer;

    public MainFrame() {
        initComponents();
        MainJPanel.removeAll();
        MainJPanel.add(Login);
        MainJPanel.revalidate();
        timer = new Timer(5000, (ActionEvent ev) -> {
                String[][] newRequests = showRequests();
                Orders_Table.setModel(new DefaultTableModel(newRequests, new String[]{"Status", "Pedido"}));
                PizzaioloForm_OrdersList2.setModel(new DefaultTableModel(newRequests, new String[]{"Status", "Pedido"}));
                EntregadorForm_OrdersList2.setModel(new DefaultTableModel(newRequests, new String[]{"Status", "Pedido"}));
        });
        timer.start();
    }

    private int LoginPower = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainJPanel = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        LoginForm_Title = new javax.swing.JLabel();
        LoginForm_UsernameLabel = new javax.swing.JLabel();
        LoginForm_UsernameField = new javax.swing.JTextField();
        LoginForm_PasswordLabel = new javax.swing.JLabel();
        LoginForm_PasswordField = new javax.swing.JTextField();
        LoginForm_LoginButton = new javax.swing.JButton();
        Admin = new javax.swing.JPanel();
        AdminForm_Name = new javax.swing.JLabel();
        AdminForm_Orders = new javax.swing.JScrollPane();
        Orders_Table = new javax.swing.JTable();
        AdminForm_OrdersLabel = new javax.swing.JLabel();
        AdminForm_RegisterOrder = new javax.swing.JButton();
        AdminForm_RegisterUser = new javax.swing.JButton();
        AdminForm_RegisterPizza = new javax.swing.JButton();
        AdminForm_FinishPizza = new javax.swing.JButton();
        AdminForm_FinishOrder = new javax.swing.JButton();
        AdminForm_Logout = new javax.swing.JButton();
        Pizzaiolo = new javax.swing.JPanel();
        PizzaioloForm_Name = new javax.swing.JLabel();
        PizzaioloForm_Orders = new javax.swing.JScrollPane();
        PizzaioloForm_OrdersList2 = new javax.swing.JTable();
        PizzaioloForm_FinishPizza = new javax.swing.JButton();
        PizzaioloForm_Logout = new javax.swing.JButton();
        PizzaioloForm_OrdersLabel = new javax.swing.JLabel();
        Entregador = new javax.swing.JPanel();
        EntregadorForm_Name = new javax.swing.JLabel();
        EntregadorForm_Orders2 = new javax.swing.JScrollPane();
        EntregadorForm_OrdersList2 = new javax.swing.JTable();
        EntregadorForm_FinishOrder = new javax.swing.JButton();
        EntregadorForm_Logout = new javax.swing.JButton();
        EntregadorForm_OrdersLabel = new javax.swing.JLabel();
        RegisterOrder = new javax.swing.JPanel();
        RegisterOrder_Title = new javax.swing.JLabel();
        RegisterOrder_PhoneNumberLabel = new javax.swing.JLabel();
        RegisterOrder_PhoneNumberField = new javax.swing.JTextField();
        RegisterOrder_NameLabel = new javax.swing.JLabel();
        RegisterOrder_NameField = new javax.swing.JTextField();
        RegisterOrder_AddressLabel = new javax.swing.JLabel();
        RegisterOrder_AddressField = new javax.swing.JTextField();
        RegisterOrder_CEPLabel = new javax.swing.JLabel();
        RegisterOrder_CEPField = new javax.swing.JTextField();
        RegisterOrder_Separator = new javax.swing.JSeparator();
        RegisterOrder_PizzaTitle = new javax.swing.JLabel();
        RegisterOrder_TasteLabel = new javax.swing.JLabel();
        RegisterOrder_SizeLabel = new javax.swing.JLabel();
        RegisterOrder_RegisterOrderButton = new javax.swing.JButton();
        RegisterOrder_SearchClientButton = new javax.swing.JButton();
        RegisterOrder_UpdateClientButton = new javax.swing.JButton();
        RegisterOrder_BackButton = new javax.swing.JButton();
        RegisterOrder_PizzaLabel = new javax.swing.JLabel();
        RegisterOrder_AddPizzaButton = new javax.swing.JButton();
        RegisterOrder_RemoveItemButton = new javax.swing.JButton();
        RegisterOrder_ItemLabel = new javax.swing.JLabel();
        RegisterOrder_ItensList = new javax.swing.JScrollPane();
        RegisterOrder_ItensList2 = new javax.swing.JList();
        RegisterOrder_DrinkLabel = new javax.swing.JLabel();
        RegisterOrder_AddDrinkButton = new javax.swing.JButton();
        RegisterOrder_SizeField = new javax.swing.JComboBox();
        RegisterOrder_TasteField1 = new javax.swing.JComboBox();
        RegisterOrder_OutroField = new javax.swing.JComboBox();
        RegisterOrder_TasteField3 = new javax.swing.JComboBox();
        RegisterOrder_TasteField2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        RegisterOrder_PriceField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        RegisterUser = new javax.swing.JPanel();
        RegisterUser_Title = new javax.swing.JLabel();
        RegisterUser_PhoneNumberLabel = new javax.swing.JLabel();
        RegisterUser_PhoneNumberField = new javax.swing.JTextField();
        RegisterUser_NameLabel = new javax.swing.JLabel();
        RegisterUser_NameField = new javax.swing.JTextField();
        RegisterUser_AddressLabel = new javax.swing.JLabel();
        RegisterUser_AddressField = new javax.swing.JTextField();
        RegisterUser_CEPLabel = new javax.swing.JLabel();
        RegisterUser_CEPField = new javax.swing.JTextField();
        RegisterUser_CPFLabel = new javax.swing.JLabel();
        RegisterUser_CPFField = new javax.swing.JTextField();
        RegisterUser_UserLabel = new javax.swing.JLabel();
        RegisterUser_UserField = new javax.swing.JTextField();
        RegisterUser_PasswordLabel = new javax.swing.JLabel();
        RegisterUser_PasswordField = new javax.swing.JTextField();
        RegisterUser_TypeLabel = new javax.swing.JLabel();
        RegisterUser_RegisterUserButton = new javax.swing.JButton();
        RegisterUser_BackButton = new javax.swing.JButton();
        RegisterUser_RoleField = new javax.swing.JComboBox();
        RegisterPizza = new javax.swing.JPanel();
        RegisterPizza_Title = new javax.swing.JLabel();
        RegisterPizza_TasteLabel = new javax.swing.JLabel();
        RegisterPizza_TasteField = new javax.swing.JTextField();
        RegisterPizza_RegisterPizzaButton = new javax.swing.JButton();
        RegisterPizza_BackButton = new javax.swing.JButton();
        RegisterPizza_PriceFieldBig = new javax.swing.JTextField();
        RegisterPizza_TasteLabel4 = new javax.swing.JLabel();
        RegisterPizza_TasteLabel5 = new javax.swing.JLabel();
        RegisterPizza_TasteLabel6 = new javax.swing.JLabel();
        RegisterPizza_OutroNameField = new javax.swing.JTextField();
        RegisterPizza_OutroPriceField = new javax.swing.JTextField();
        RegisterPizza_TasteLabel7 = new javax.swing.JLabel();
        RegisterPizza_Title1 = new javax.swing.JLabel();
        RegisterPizza_RegisterPizzaButton1 = new javax.swing.JButton();
        RegisterPizza_TasteLabel1 = new javax.swing.JLabel();
        RegisterPizza_PriceFieldMedium = new javax.swing.JTextField();
        RegisterPizza_PriceFieldFamily = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainJPanel.setLayout(new java.awt.CardLayout());

        LoginForm_Title.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        LoginForm_Title.setText("Login");

        LoginForm_UsernameLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        LoginForm_UsernameLabel.setText("Usuário");

        LoginForm_UsernameField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        LoginForm_PasswordLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        LoginForm_PasswordLabel.setText("Senha");

        LoginForm_PasswordField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        LoginForm_PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginForm_PasswordFieldActionPerformed(evt);
            }
        });
        LoginForm_PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginForm_PasswordFieldKeyPressed(evt);
            }
        });

        LoginForm_LoginButton.setText("Login");
        LoginForm_LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginForm_LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginForm_LoginButton)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoginForm_UsernameLabel)
                            .addComponent(LoginForm_PasswordLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginForm_UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoginForm_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LoginForm_Title))
                .addContainerGap(585, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LoginForm_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginForm_UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginForm_UsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginForm_PasswordLabel)
                    .addComponent(LoginForm_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LoginForm_LoginButton)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        MainJPanel.add(Login, "card2");

        AdminForm_Name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        AdminForm_Name.setText("Administrador: Nome");

        AdminForm_Orders.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        Orders_Table.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Orders_Table.setModel(new DefaultTableModel(showRequests(), new String[]{"Status", "Pedido"}));
        AdminForm_Orders.setViewportView(Orders_Table);

        AdminForm_OrdersLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        AdminForm_OrdersLabel.setText("Pedidos");

        AdminForm_RegisterOrder.setText("Cadastrar Pedido/Cliente");
        AdminForm_RegisterOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_RegisterOrderActionPerformed(evt);
            }
        });

        AdminForm_RegisterUser.setText("Cadastrar Usuário");
        AdminForm_RegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_RegisterUserActionPerformed(evt);
            }
        });

        AdminForm_RegisterPizza.setText("Cadastrar Produto");
        AdminForm_RegisterPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_RegisterPizzaActionPerformed(evt);
            }
        });

        AdminForm_FinishPizza.setText("Finalizar Pizza");
        AdminForm_FinishPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_FinishPizzaActionPerformed(evt);
            }
        });

        AdminForm_FinishOrder.setText("Finalizar Entrega");
        AdminForm_FinishOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_FinishOrderActionPerformed(evt);
            }
        });

        AdminForm_Logout.setText("Deslogar");
        AdminForm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
        Admin.setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminForm_OrdersLabel)
                    .addComponent(AdminForm_Name)
                    .addComponent(AdminForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdminLayout.createSequentialGroup()
                        .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminForm_RegisterOrder)
                            .addComponent(AdminForm_FinishPizza))
                        .addGap(18, 18, 18)
                        .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminForm_FinishOrder)
                            .addGroup(AdminLayout.createSequentialGroup()
                                .addComponent(AdminForm_RegisterPizza)
                                .addGap(28, 28, 28)
                                .addComponent(AdminForm_RegisterUser)))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminForm_Logout)
                .addContainerGap())
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminForm_Logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminForm_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminForm_RegisterOrder)
                    .addComponent(AdminForm_RegisterUser)
                    .addComponent(AdminForm_RegisterPizza))
                .addGap(18, 18, 18)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminForm_FinishPizza)
                    .addComponent(AdminForm_FinishOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(AdminForm_OrdersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainJPanel.add(Admin, "card2");

        PizzaioloForm_Name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        PizzaioloForm_Name.setText("Pizzaiolo: Nome");

        PizzaioloForm_OrdersList2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        PizzaioloForm_OrdersList2.setModel(new DefaultTableModel(showRequests(), new String[]{"Status", "Pedido"}));
        PizzaioloForm_Orders.setViewportView(PizzaioloForm_OrdersList2);

        PizzaioloForm_FinishPizza.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        PizzaioloForm_FinishPizza.setText("Finalizar Pizza");
        PizzaioloForm_FinishPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaioloForm_FinishPizzaActionPerformed(evt);
            }
        });

        PizzaioloForm_Logout.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        PizzaioloForm_Logout.setText("Deslogar");
        PizzaioloForm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaioloForm_LogoutActionPerformed(evt);
            }
        });

        PizzaioloForm_OrdersLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        PizzaioloForm_OrdersLabel.setText("Pedidos");

        javax.swing.GroupLayout PizzaioloLayout = new javax.swing.GroupLayout(Pizzaiolo);
        Pizzaiolo.setLayout(PizzaioloLayout);
        PizzaioloLayout.setHorizontalGroup(
            PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PizzaioloLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PizzaioloForm_OrdersLabel)
                    .addGroup(PizzaioloLayout.createSequentialGroup()
                        .addComponent(PizzaioloForm_FinishPizza)
                        .addGap(18, 18, 18)
                        .addComponent(PizzaioloForm_Logout))
                    .addComponent(PizzaioloForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PizzaioloForm_Name))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        PizzaioloLayout.setVerticalGroup(
            PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PizzaioloLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(PizzaioloForm_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PizzaioloForm_FinishPizza)
                    .addComponent(PizzaioloForm_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(PizzaioloForm_OrdersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PizzaioloForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainJPanel.add(Pizzaiolo, "card2");

        EntregadorForm_Name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        EntregadorForm_Name.setText("Entregador: Nome");

        EntregadorForm_OrdersList2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        EntregadorForm_OrdersList2.setModel(new DefaultTableModel(showRequests(), new String[]{"Status", "Pedido"}));
        EntregadorForm_Orders2.setViewportView(EntregadorForm_OrdersList2);

        EntregadorForm_FinishOrder.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        EntregadorForm_FinishOrder.setText("Finalizar Entrega");
        EntregadorForm_FinishOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntregadorForm_FinishOrderActionPerformed(evt);
            }
        });

        EntregadorForm_Logout.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        EntregadorForm_Logout.setText("Deslogar");
        EntregadorForm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntregadorForm_LogoutActionPerformed(evt);
            }
        });

        EntregadorForm_OrdersLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        EntregadorForm_OrdersLabel.setText("Pedidos");

        javax.swing.GroupLayout EntregadorLayout = new javax.swing.GroupLayout(Entregador);
        Entregador.setLayout(EntregadorLayout);
        EntregadorLayout.setHorizontalGroup(
            EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntregadorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EntregadorForm_OrdersLabel)
                    .addGroup(EntregadorLayout.createSequentialGroup()
                        .addComponent(EntregadorForm_FinishOrder)
                        .addGap(18, 18, 18)
                        .addComponent(EntregadorForm_Logout))
                    .addComponent(EntregadorForm_Orders2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntregadorForm_Name))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        EntregadorLayout.setVerticalGroup(
            EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntregadorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(EntregadorForm_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntregadorForm_FinishOrder)
                    .addComponent(EntregadorForm_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(EntregadorForm_OrdersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EntregadorForm_Orders2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainJPanel.add(Entregador, "card2");

        RegisterOrder_Title.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        RegisterOrder_Title.setText("Registrar Pedido");

        RegisterOrder_PhoneNumberLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RegisterOrder_PhoneNumberLabel.setText("Telefone");

        RegisterOrder_PhoneNumberField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RegisterOrder_PhoneNumberField.setToolTipText("");

        RegisterOrder_NameLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RegisterOrder_NameLabel.setText("Nome");

        RegisterOrder_NameField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        RegisterOrder_AddressLabel.setText("Endereço");

        RegisterOrder_CEPLabel.setText("CEP");

        RegisterOrder_PizzaTitle.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        RegisterOrder_PizzaTitle.setText("Pedido");

        RegisterOrder_TasteLabel.setText("Sabores");

        RegisterOrder_SizeLabel.setText("Tamanho");

        RegisterOrder_RegisterOrderButton.setText("Realizar Pedido");
        RegisterOrder_RegisterOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_RegisterOrderButtonActionPerformed(evt);
            }
        });

        RegisterOrder_SearchClientButton.setText("Procurar");
        RegisterOrder_SearchClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_SearchClientButtonActionPerformed(evt);
            }
        });

        RegisterOrder_UpdateClientButton.setText("Atualizar ou Registrar Novo Cliente");
        RegisterOrder_UpdateClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_UpdateClientButtonActionPerformed(evt);
            }
        });

        RegisterOrder_BackButton.setText("Voltar");
        RegisterOrder_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_BackButtonActionPerformed(evt);
            }
        });

        RegisterOrder_PizzaLabel.setText("Pizza");

        RegisterOrder_AddPizzaButton.setText("Adicionar");
        RegisterOrder_AddPizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_AddPizzaButtonActionPerformed(evt);
            }
        });

        RegisterOrder_RemoveItemButton.setText("Remover");

        RegisterOrder_ItemLabel.setText("Itens");

        RegisterOrder_ItensList2.setModel(new DefaultListModel());
        RegisterOrder_ItensList.setViewportView(RegisterOrder_ItensList2);

        RegisterOrder_DrinkLabel.setText("Outros");

        RegisterOrder_AddDrinkButton.setText("Adicionar");
        RegisterOrder_AddDrinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_AddDrinkButtonActionPerformed(evt);
            }
        });

        RegisterOrder_SizeField.setModel(new DefaultComboBoxModel(PizzaTaste.Size.values()));
        RegisterOrder_SizeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_SizeFieldActionPerformed(evt);
            }
        });

        RegisterOrder_TasteField1.setModel(new DefaultComboBoxModel(getTasteList()));
        RegisterOrder_TasteField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_TasteField1ActionPerformed(evt);
            }
        });

        RegisterOrder_OutroField.setModel(new DefaultComboBoxModel(getDrinkList()));
        RegisterOrder_OutroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_OutroFieldActionPerformed(evt);
            }
        });

        RegisterOrder_TasteField3.setModel(new DefaultComboBoxModel(getTasteList()));
        RegisterOrder_TasteField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_TasteField3ActionPerformed(evt);
            }
        });

        RegisterOrder_TasteField2.setModel(new DefaultComboBoxModel(getTasteList()));
        RegisterOrder_TasteField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_TasteField2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Preço:");

        RegisterOrder_PriceField.setText("R$" + String.valueOf(setPizzaPrice()));

        jButton1.setText("Deslogar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterOrderLayout = new javax.swing.GroupLayout(RegisterOrder);
        RegisterOrder.setLayout(RegisterOrderLayout);
        RegisterOrderLayout.setHorizontalGroup(
            RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterOrderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterOrderLayout.createSequentialGroup()
                                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RegisterOrder_NameLabel)
                                    .addComponent(RegisterOrder_PhoneNumberLabel)
                                    .addComponent(RegisterOrder_AddressLabel)
                                    .addComponent(RegisterOrder_CEPLabel))
                                .addGap(18, 18, 18)
                                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                                        .addComponent(RegisterOrder_PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(RegisterOrder_SearchClientButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(RegisterOrder_UpdateClientButton))
                                    .addComponent(RegisterOrder_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterOrder_AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterOrder_CEPField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(RegisterOrderLayout.createSequentialGroup()
                                    .addComponent(RegisterOrder_Title)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RegisterOrder_BackButton))
                                .addGroup(RegisterOrderLayout.createSequentialGroup()
                                    .addComponent(RegisterOrder_PizzaTitle)
                                    .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(RegisterOrderLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(RegisterOrder_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(RegisterOrderLayout.createSequentialGroup()
                                            .addGap(71, 71, 71)
                                            .addComponent(RegisterOrder_PizzaLabel)
                                            .addGap(194, 194, 194)
                                            .addComponent(RegisterOrder_ItemLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(RegisterOrder_DrinkLabel)
                                            .addGap(132, 132, 132))))))
                        .addContainerGap())
                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterOrderLayout.createSequentialGroup()
                                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(RegisterOrder_SizeLabel)
                                    .addComponent(RegisterOrder_TasteLabel))
                                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RegisterOrder_TasteField2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RegisterOrder_SizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RegisterOrder_TasteField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RegisterOrder_TasteField3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(RegisterOrder_PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(RegisterOrderLayout.createSequentialGroup()
                                .addComponent(RegisterOrder_AddPizzaButton)
                                .addGap(18, 18, 18)
                                .addComponent(RegisterOrder_RemoveItemButton)))
                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterOrderLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(RegisterOrder_RegisterOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(RegisterOrderLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(RegisterOrder_ItensList, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(RegisterOrder_AddDrinkButton)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RegisterOrder_OutroField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61))))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterOrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterOrderLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterOrderLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(352, 352, 352))))
        );
        RegisterOrderLayout.setVerticalGroup(
            RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterOrder_Title)
                    .addComponent(RegisterOrder_BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterOrder_PhoneNumberLabel)
                    .addComponent(RegisterOrder_PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterOrder_SearchClientButton)
                    .addComponent(RegisterOrder_UpdateClientButton))
                .addGap(18, 18, 18)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterOrder_NameLabel)
                    .addComponent(RegisterOrder_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterOrder_AddressLabel)
                    .addComponent(RegisterOrder_AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterOrder_CEPLabel)
                    .addComponent(RegisterOrder_CEPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterOrder_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterOrder_PizzaTitle)
                            .addComponent(RegisterOrder_PizzaLabel)
                            .addComponent(RegisterOrder_DrinkLabel)
                            .addComponent(RegisterOrder_ItemLabel))
                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterOrderLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(RegisterOrder_OutroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(RegisterOrder_AddDrinkButton))
                            .addGroup(RegisterOrderLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RegisterOrder_ItensList, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(RegisterOrder_TasteField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterOrder_TasteField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterOrder_TasteLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegisterOrder_TasteField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterOrder_SizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterOrder_SizeLabel))
                        .addGap(15, 15, 15)
                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(RegisterOrder_PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterOrder_AddPizzaButton)
                    .addComponent(RegisterOrder_RemoveItemButton)
                    .addComponent(RegisterOrder_RegisterOrderButton))
                .addContainerGap())
        );

        MainJPanel.add(RegisterOrder, "card2");

        RegisterUser_Title.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        RegisterUser_Title.setText("Registrar Usuário");

        RegisterUser_PhoneNumberLabel.setText("Telefone");

        RegisterUser_NameLabel.setText("Nome");

        RegisterUser_AddressLabel.setText("Endereço");

        RegisterUser_CEPLabel.setText("CEP");

        RegisterUser_CPFLabel.setText("CPF");

        RegisterUser_UserLabel.setText("Usuário");

        RegisterUser_PasswordLabel.setText("Senha");

        RegisterUser_TypeLabel.setText("Tipo");

        RegisterUser_RegisterUserButton.setText("Registrar Novo Usuário");
        RegisterUser_RegisterUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUser_RegisterUserButtonActionPerformed(evt);
            }
        });

        RegisterUser_BackButton.setText("Voltar");
        RegisterUser_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUser_BackButtonActionPerformed(evt);
            }
        });

        RegisterUser_RoleField.setModel(new DefaultComboBoxModel(pizzasystem.data.Employee.Role.values()));
        RegisterUser_RoleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUser_RoleFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterUserLayout = new javax.swing.GroupLayout(RegisterUser);
        RegisterUser.setLayout(RegisterUserLayout);
        RegisterUserLayout.setHorizontalGroup(
            RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterUserLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterUser_Title)
                    .addGroup(RegisterUserLayout.createSequentialGroup()
                        .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegisterUser_NameLabel)
                            .addComponent(RegisterUser_PhoneNumberLabel)
                            .addComponent(RegisterUser_AddressLabel)
                            .addComponent(RegisterUser_CEPLabel)
                            .addComponent(RegisterUser_CPFLabel))
                        .addGap(18, 18, 18)
                        .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterUser_AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterUser_CPFField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegisterUserLayout.createSequentialGroup()
                                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisterUser_PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterUser_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterUser_CEPField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(171, 171, 171)
                                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisterUser_UserLabel)
                                    .addComponent(RegisterUser_PasswordLabel)
                                    .addComponent(RegisterUser_TypeLabel))
                                .addGap(18, 18, 18)
                                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegisterUserLayout.createSequentialGroup()
                                        .addComponent(RegisterUser_UserField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                        .addComponent(RegisterUser_BackButton))
                                    .addGroup(RegisterUserLayout.createSequentialGroup()
                                        .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(RegisterUser_PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(RegisterUser_RoleField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addComponent(RegisterUser_RegisterUserButton))
                .addGap(40, 40, 40))
        );
        RegisterUserLayout.setVerticalGroup(
            RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterUserLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterUserLayout.createSequentialGroup()
                        .addComponent(RegisterUser_Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterUser_PhoneNumberLabel)
                            .addComponent(RegisterUser_PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterUser_UserLabel)
                            .addComponent(RegisterUser_UserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(RegisterUser_BackButton))
                .addGap(18, 18, 18)
                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterUser_NameLabel)
                    .addComponent(RegisterUser_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterUser_PasswordLabel)
                    .addComponent(RegisterUser_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterUser_AddressLabel)
                    .addComponent(RegisterUser_AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterUser_CEPLabel)
                    .addComponent(RegisterUser_CEPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterUser_TypeLabel)
                    .addComponent(RegisterUser_RoleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterUser_CPFLabel)
                    .addComponent(RegisterUser_CPFField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(RegisterUser_RegisterUserButton)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        MainJPanel.add(RegisterUser, "card2");

        RegisterPizza_Title.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        RegisterPizza_Title.setText("Registrar outro produto");

        RegisterPizza_TasteLabel.setText("Preço Big:");

        RegisterPizza_RegisterPizzaButton.setText("Registrar Nova Pizza");
        RegisterPizza_RegisterPizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPizza_RegisterPizzaButtonActionPerformed(evt);
            }
        });

        RegisterPizza_BackButton.setText("Voltar");
        RegisterPizza_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPizza_BackButtonActionPerformed(evt);
            }
        });

        RegisterPizza_PriceFieldBig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPizza_PriceFieldBigActionPerformed(evt);
            }
        });

        RegisterPizza_TasteLabel4.setText("Sabor");

        RegisterPizza_TasteLabel5.setText("Preço Family:");

        RegisterPizza_TasteLabel6.setText("Produto:");

        RegisterPizza_TasteLabel7.setText("Preço:");

        RegisterPizza_Title1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        RegisterPizza_Title1.setText("Registrar Pizza");

        RegisterPizza_RegisterPizzaButton1.setText("Registrar novo produto");
        RegisterPizza_RegisterPizzaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPizza_RegisterPizzaButton1ActionPerformed(evt);
            }
        });

        RegisterPizza_TasteLabel1.setText("Preço Medium:");

        javax.swing.GroupLayout RegisterPizzaLayout = new javax.swing.GroupLayout(RegisterPizza);
        RegisterPizza.setLayout(RegisterPizzaLayout);
        RegisterPizzaLayout.setHorizontalGroup(
            RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPizzaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterPizza_BackButton)
                .addGap(25, 25, 25))
            .addGroup(RegisterPizzaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterPizzaLayout.createSequentialGroup()
                        .addComponent(RegisterPizza_Title1)
                        .addGap(121, 121, 121)
                        .addComponent(RegisterPizza_TasteLabel5)
                        .addGap(86, 86, 86)
                        .addComponent(RegisterPizza_TasteLabel))
                    .addComponent(RegisterPizza_RegisterPizzaButton1)
                    .addComponent(RegisterPizza_Title)
                    .addGroup(RegisterPizzaLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(RegisterPizza_TasteLabel7))
                    .addComponent(RegisterPizza_RegisterPizzaButton)
                    .addGroup(RegisterPizzaLayout.createSequentialGroup()
                        .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterPizzaLayout.createSequentialGroup()
                                .addComponent(RegisterPizza_TasteLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(RegisterPizza_OutroNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegisterPizzaLayout.createSequentialGroup()
                                .addComponent(RegisterPizza_TasteLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(RegisterPizza_TasteField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78)
                        .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterPizzaLayout.createSequentialGroup()
                                .addComponent(RegisterPizza_PriceFieldFamily, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(RegisterPizza_PriceFieldBig, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RegisterPizza_OutroPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterPizzaLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(RegisterPizza_TasteLabel1))
                    .addGroup(RegisterPizzaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(RegisterPizza_PriceFieldMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        RegisterPizzaLayout.setVerticalGroup(
            RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPizzaLayout.createSequentialGroup()
                .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterPizzaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(RegisterPizza_Title1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterPizza_TasteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterPizza_TasteLabel4)
                            .addComponent(RegisterPizza_PriceFieldFamily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterPizza_PriceFieldBig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterPizza_PriceFieldMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegisterPizzaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterPizza_TasteLabel5)
                            .addComponent(RegisterPizza_TasteLabel)
                            .addComponent(RegisterPizza_TasteLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterPizza_RegisterPizzaButton)
                .addGap(28, 28, 28)
                .addComponent(RegisterPizza_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterPizza_TasteLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterPizza_OutroNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterPizza_OutroPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterPizza_TasteLabel6))
                .addGap(18, 18, 18)
                .addComponent(RegisterPizza_RegisterPizzaButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(RegisterPizza_BackButton)
                .addGap(23, 23, 23))
        );

        MainJPanel.add(RegisterPizza, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginForm_LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginForm_LoginButtonActionPerformed
        Login();
    }//GEN-LAST:event_LoginForm_LoginButtonActionPerformed

    private void AdminForm_RegisterOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_RegisterOrderActionPerformed
        // TODO add your handling code here:
        this.RegisterOrder();
    }//GEN-LAST:event_AdminForm_RegisterOrderActionPerformed

    private void AdminForm_RegisterPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_RegisterPizzaActionPerformed
        // TODO add your handling code here:
        this.RegisterPizza();
    }//GEN-LAST:event_AdminForm_RegisterPizzaActionPerformed

    private void AdminForm_FinishPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_FinishPizzaActionPerformed
        // TODO add your handling code here:
        this.FinishPizza();
    }//GEN-LAST:event_AdminForm_FinishPizzaActionPerformed

    private void AdminForm_FinishOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_FinishOrderActionPerformed
        // TODO add your handling code here:
        this.FinishOrder();
    }//GEN-LAST:event_AdminForm_FinishOrderActionPerformed

    private void AdminForm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_LogoutActionPerformed
        Main.getPizzaria().setCurrentUser(null);
        this.Logout();
    }//GEN-LAST:event_AdminForm_LogoutActionPerformed

    private void PizzaioloForm_FinishPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaioloForm_FinishPizzaActionPerformed
        // TODO add your handling code here:
        this.FinishPizza();
    }//GEN-LAST:event_PizzaioloForm_FinishPizzaActionPerformed

    private void PizzaioloForm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaioloForm_LogoutActionPerformed
        Main.getPizzaria().setCurrentUser(null);
        this.Logout();
    }//GEN-LAST:event_PizzaioloForm_LogoutActionPerformed

    private void EntregadorForm_FinishOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntregadorForm_FinishOrderActionPerformed
        // TODO add your handling code here:
        this.FinishOrder();
    }//GEN-LAST:event_EntregadorForm_FinishOrderActionPerformed

    private void EntregadorForm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntregadorForm_LogoutActionPerformed
        Main.getPizzaria().setCurrentUser(null);
        this.Logout();
    }//GEN-LAST:event_EntregadorForm_LogoutActionPerformed

    private void RegisterOrder_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_BackButtonActionPerformed
        // TODO add your handling code here:
        if (LoginPower == 1){
            this.GoBack();
        }else{
            JOptionPane.showMessageDialog(null, "Opção disponivel apenas para administrador");
        }
    }//GEN-LAST:event_RegisterOrder_BackButtonActionPerformed

    private void RegisterUser_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUser_BackButtonActionPerformed
        // TODO add your handling code here:
        this.GoBack();
    }//GEN-LAST:event_RegisterUser_BackButtonActionPerformed

    private void RegisterPizza_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPizza_BackButtonActionPerformed
        // TODO add your handling code here:
        this.GoBack();
    }//GEN-LAST:event_RegisterPizza_BackButtonActionPerformed

    private void RegisterOrder_SearchClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_SearchClientButtonActionPerformed
        String number = (RegisterOrder_PhoneNumberField.getText());
        try {
            Person client = Main.getPizzaria().findClient(number);
            if (client == null)
                return;
            RegisterOrder_AddressField.setText(client.getAddress());
            RegisterOrder_CEPField.setText(client.getCep());
            RegisterOrder_NameField.setText(client.getName());
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Falha na comunicação com banco de dados");
        }
    }//GEN-LAST:event_RegisterOrder_SearchClientButtonActionPerformed

    private void RegisterOrder_UpdateClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_UpdateClientButtonActionPerformed
        Person person = new Person();
        person.setAddress(RegisterOrder_AddressField.getText());
        person.setCep(RegisterOrder_CEPField.getText());
        person.setName(RegisterOrder_NameField.getText());
        person.setPhoneNumber(RegisterOrder_PhoneNumberField.getText());
        try {
            Main.getPizzaria().addClient(person);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Falha na comunicação com banco de dados");
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_RegisterOrder_UpdateClientButtonActionPerformed

    private void RegisterPizza_RegisterPizzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPizza_RegisterPizzaButtonActionPerformed
        PizzaTaste newPizzaTaste = new PizzaTaste();
        newPizzaTaste.setPriceFamily(Float.parseFloat(RegisterPizza_PriceFieldFamily.getText()));
        newPizzaTaste.setPriceBig(Float.parseFloat(RegisterPizza_PriceFieldBig.getText()));
        newPizzaTaste.setPriceMedium(Float.parseFloat(RegisterPizza_PriceFieldMedium.getText()));
        newPizzaTaste.setName(RegisterPizza_TasteField.getText());
        try {
            Main.getPizzaria().registerPizza(newPizzaTaste);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha na comunicação com banco de dados");
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            RegisterOrder_TasteField1.addItem(newPizzaTaste.getName());
            RegisterOrder_TasteField2.addItem(newPizzaTaste.getName());
            RegisterOrder_TasteField3.addItem(newPizzaTaste.getName());
        }
    }//GEN-LAST:event_RegisterPizza_RegisterPizzaButtonActionPerformed

    private void RegisterOrder_TasteField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_TasteField1ActionPerformed
        setPizzaPrice();
    }//GEN-LAST:event_RegisterOrder_TasteField1ActionPerformed

    private void RegisterOrder_OutroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_OutroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterOrder_OutroFieldActionPerformed

    private void RegisterOrder_TasteField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_TasteField3ActionPerformed
        setPizzaPrice();
    }//GEN-LAST:event_RegisterOrder_TasteField3ActionPerformed

    private void RegisterOrder_TasteField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_TasteField2ActionPerformed
        setPizzaPrice();
    }//GEN-LAST:event_RegisterOrder_TasteField2ActionPerformed

    private void RegisterPizza_RegisterPizzaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPizza_RegisterPizzaButton1ActionPerformed
        OtherProductType outro = new OtherProductType();
        outro.setName(RegisterPizza_OutroNameField.getText());
        outro.setPrice(Float.parseFloat(RegisterPizza_OutroPriceField.getText()));
        try{
            Main.getPizzaria().registerOutro(outro);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Falha na comunicação com banco de dados");    
        } catch(RuntimeException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            RegisterOrder_OutroField.addItem(outro.getName());
        }
    }//GEN-LAST:event_RegisterPizza_RegisterPizzaButton1ActionPerformed

    private void RegisterUser_RegisterUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUser_RegisterUserButtonActionPerformed
        PasswordHasher hasher = new PasswordHasher();
        Employee newemployee = new Employee();
        newemployee.setAddress(RegisterUser_AddressField.getText());
        newemployee.setCep(RegisterUser_CEPField.getText());
        newemployee.setCpf(RegisterUser_CPFField.getText());
        newemployee.setHashPass(hasher.hash(RegisterUser_PasswordField.getText()));
        newemployee.setName(RegisterUser_NameField.getText());
        newemployee.setPhoneNumber(RegisterUser_PhoneNumberField.getText());
        newemployee.setRole((Role) RegisterUser_RoleField.getSelectedItem());
        newemployee.setUser(RegisterUser_UserField.getText());
        try {
            Main.getPizzaria().registerEmployee(newemployee);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Falha na comunicação com banco de dados");
        } catch (RuntimeException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_RegisterUser_RegisterUserButtonActionPerformed

    private void RegisterUser_RoleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUser_RoleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterUser_RoleFieldActionPerformed

    private void RegisterOrder_AddPizzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_AddPizzaButtonActionPerformed
        DefaultListModel lista = (DefaultListModel) RegisterOrder_ItensList2.getModel();
        lista.addElement(RegisterOrder_TasteField1.getSelectedItem() + ", " + RegisterOrder_TasteField2.getSelectedItem() + ", " + RegisterOrder_TasteField3.getSelectedItem());
        RegisterOrder_ItensList2.setModel(lista);
        if (this.currentRequest != null){
            Pizza newPizza = new Pizza();
            newPizza.setTaste1((String) RegisterOrder_TasteField1.getSelectedItem());
            newPizza.setTaste2((String) RegisterOrder_TasteField2.getSelectedItem());
            newPizza.setTaste3((String) RegisterOrder_TasteField3.getSelectedItem());
            newPizza.setSize((Size) RegisterOrder_SizeField.getSelectedItem());
            ArrayList<Pizza> pizzas = (ArrayList<Pizza>) currentRequest.getPizzas();
            pizzas.add(newPizza);
            currentRequest.setPizzas(pizzas);
        }else{
            this.currentRequest = new ClientRequest();
            Pizza newPizza = new Pizza();
            newPizza.setTaste1((String) RegisterOrder_TasteField1.getSelectedItem());
            newPizza.setTaste2((String) RegisterOrder_TasteField2.getSelectedItem());
            newPizza.setTaste3((String) RegisterOrder_TasteField3.getSelectedItem());
            newPizza.setSize((Size) RegisterOrder_SizeField.getSelectedItem());
            ArrayList<Pizza> pizzas = (ArrayList<Pizza>) currentRequest.getPizzas();
            pizzas.add(newPizza);
            currentRequest.setPizzas(pizzas);
        }
    }//GEN-LAST:event_RegisterOrder_AddPizzaButtonActionPerformed

    private void RegisterOrder_AddDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_AddDrinkButtonActionPerformed
        DefaultListModel lista = (DefaultListModel) RegisterOrder_ItensList2.getModel();
        lista.addElement(RegisterOrder_OutroField.getSelectedItem());
        RegisterOrder_ItensList2.setModel(lista);
        if (this.currentRequest != null){
            OtherProductType newOutro = new OtherProductType();
            newOutro.setName((String) RegisterOrder_OutroField.getSelectedItem());
            try {
                newOutro.setPrice(Main.getPizzaria().findOtherProduct((String) RegisterOrder_OutroField.getSelectedItem()).getPrice());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Falha na comunicação com banco de dados");
            }
            ArrayList<OtherProductType> newOthers = currentRequest.getOthers();
            newOthers.add(newOutro);
            currentRequest.setOthers(newOthers);
        }else{
            this.currentRequest = new ClientRequest();
            OtherProductType newOutro = new OtherProductType();
            newOutro.setName((String) RegisterOrder_OutroField.getSelectedItem());
            try {
                newOutro.setPrice(Main.getPizzaria().findOtherProduct((String) RegisterOrder_OutroField.getSelectedItem()).getPrice());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Falha na comunicação com banco de dados");
            }
            ArrayList<OtherProductType> newOthers = currentRequest.getOthers();
            newOthers.add(newOutro);
            currentRequest.setOthers(newOthers);
        }
    }//GEN-LAST:event_RegisterOrder_AddDrinkButtonActionPerformed

    private void RegisterOrder_RegisterOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_RegisterOrderButtonActionPerformed
        currentRequest.setStatus(Status.Requested);
        try {
            currentRequest.setClient(Main.getPizzaria().findClient(RegisterOrder_PhoneNumberField.getText()));
            Main.getPizzaria().addRequest(currentRequest);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha na comunicação com banco de dados");
        } catch (RuntimeException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        currentRequest = null;
        RegisterOrder_ItensList2.setModel(new DefaultListModel());
    }//GEN-LAST:event_RegisterOrder_RegisterOrderButtonActionPerformed

    private void LoginForm_PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginForm_PasswordFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.Login();
        }
    }//GEN-LAST:event_LoginForm_PasswordFieldKeyPressed

    private void RegisterOrder_SizeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_SizeFieldActionPerformed
        setPizzaPrice();
    }//GEN-LAST:event_RegisterOrder_SizeFieldActionPerformed

    private void AdminForm_RegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_RegisterUserActionPerformed
        // TODO add your handling code here:
        this.RegisterUser();
    }//GEN-LAST:event_AdminForm_RegisterUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main.getPizzaria().setCurrentUser(null);
        this.Logout();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegisterPizza_PriceFieldBigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPizza_PriceFieldBigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterPizza_PriceFieldBigActionPerformed

    private void LoginForm_PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginForm_PasswordFieldActionPerformed

    }//GEN-LAST:event_LoginForm_PasswordFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        currentRequest = null;
        RegisterOrder_ItensList2.setModel(new DefaultListModel());
    }//GEN-LAST:event_jButton2ActionPerformed

    private String[][] showRequests(){
        String[][] output2;
        ArrayList<String[]> output = new ArrayList<>();
        List<ClientRequest> requestsList = null;
        try {
            requestsList = Main.getPizzaria().getRequests();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha na comunicação com banco de dados");
        }
        for(ClientRequest request : requestsList){
            String[] row = new String[2];
            row[0] = request.getStatus().toString();
            for(Pizza pizza : request.getPizzas()){
                if(row[1] == null){
                    row[1] = "*" + pizza.getSize() + ":" + pizza.getTaste1() + "-" + pizza.getTaste2() + "-" + pizza.getTaste3() + "* ";
                }else{
                    row[1] += "*" + pizza.getSize() + ":" + pizza.getTaste1() + " " + pizza.getTaste2() + " " + pizza.getTaste3() + "* ";
                }
            }
            for(OtherProductType other : request.getOthers()){
                if(row[1] == null){
                    row[1] = "*" + other.getName() + "* ";
                }else{
                    row[1] += "*" + other.getName() + "* ";
                }
            }
            
            output.add(row);
        }
        output2 = output.toArray(new String[requestsList.size()][]);
        return output2;
    }

    private void RegisterOrder() {
        MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();

            MainJPanel.add(RegisterOrder);
            MainJPanel.repaint();
            MainJPanel.revalidate();
    }

    private void RegisterUser() {
        MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();

            MainJPanel.add(RegisterUser);
            MainJPanel.repaint();
            MainJPanel.revalidate();
    }

    private void RegisterPizza() {
        MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();

            MainJPanel.add(RegisterPizza);
            MainJPanel.repaint();
            MainJPanel.revalidate();
    }

    private void FinishPizza() {
       // Main.getPizzaria().finishPizza();
    }

    private void FinishOrder() {
       // Main.getPizzaria().finishOrder();
    }

    private void Logout() {
        MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();

            MainJPanel.add(Login);
            MainJPanel.repaint();
            MainJPanel.revalidate();
    }

    private void Login(){
        try {
            this.LoginPower = Main.getPizzaria().doLogin(LoginForm_UsernameField.getText(), LoginForm_PasswordField.getText());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Falha na comunicação com banco de dados");
        }
        switch(this.LoginPower) {
            case 0:
                JOptionPane.showMessageDialog(null, "Não foi possivel fazer login");
                return;
            case 1:
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();
                MainJPanel.add(Admin);
                MainJPanel.repaint();
                MainJPanel.revalidate();
                return;
            case 2:
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();
                MainJPanel.add(RegisterOrder);
                MainJPanel.repaint();
                MainJPanel.revalidate();
                return;
            case 3:
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();
                MainJPanel.add(Pizzaiolo);
                MainJPanel.repaint();
                MainJPanel.revalidate();
                return;
            case 4:
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();
                MainJPanel.add(Entregador);
                MainJPanel.repaint();
                MainJPanel.revalidate();
        }

    }

    private void GoBack() {
        switch(this.LoginPower) {
            case 1: // admin
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();

                MainJPanel.add(Admin);
                MainJPanel.repaint();
                MainJPanel.revalidate();
                break;
            case 2: // atendente
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();

                MainJPanel.add(RegisterOrder);
                MainJPanel.repaint();
                MainJPanel.revalidate();
                break;
            case 3: // pizzaiolo
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();

                MainJPanel.add(Pizzaiolo);
                MainJPanel.repaint();
                MainJPanel.revalidate();
                break;
            case 4: // entregador
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();

                MainJPanel.add(Entregador);
                MainJPanel.repaint();
                MainJPanel.revalidate();
                break;
            default: // outros(teste/error)
                this.Logout();
                break;

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    private javax.swing.JButton AdminForm_FinishOrder;
    private javax.swing.JButton AdminForm_FinishPizza;
    private javax.swing.JButton AdminForm_Logout;
    private javax.swing.JLabel AdminForm_Name;
    private javax.swing.JScrollPane AdminForm_Orders;
    private javax.swing.JLabel AdminForm_OrdersLabel;
    private javax.swing.JButton AdminForm_RegisterOrder;
    private javax.swing.JButton AdminForm_RegisterPizza;
    private javax.swing.JButton AdminForm_RegisterUser;
    private javax.swing.JPanel Entregador;
    private javax.swing.JButton EntregadorForm_FinishOrder;
    private javax.swing.JButton EntregadorForm_Logout;
    private javax.swing.JLabel EntregadorForm_Name;
    private javax.swing.JScrollPane EntregadorForm_Orders2;
    private javax.swing.JLabel EntregadorForm_OrdersLabel;
    private javax.swing.JTable EntregadorForm_OrdersList2;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginForm_LoginButton;
    private javax.swing.JTextField LoginForm_PasswordField;
    private javax.swing.JLabel LoginForm_PasswordLabel;
    private javax.swing.JLabel LoginForm_Title;
    private javax.swing.JTextField LoginForm_UsernameField;
    private javax.swing.JLabel LoginForm_UsernameLabel;
    private javax.swing.JPanel MainJPanel;
    private javax.swing.JTable Orders_Table;
    private javax.swing.JPanel Pizzaiolo;
    private javax.swing.JButton PizzaioloForm_FinishPizza;
    private javax.swing.JButton PizzaioloForm_Logout;
    private javax.swing.JLabel PizzaioloForm_Name;
    private javax.swing.JScrollPane PizzaioloForm_Orders;
    private javax.swing.JLabel PizzaioloForm_OrdersLabel;
    private javax.swing.JTable PizzaioloForm_OrdersList2;
    private javax.swing.JPanel RegisterOrder;
    private javax.swing.JButton RegisterOrder_AddDrinkButton;
    private javax.swing.JButton RegisterOrder_AddPizzaButton;
    private javax.swing.JTextField RegisterOrder_AddressField;
    private javax.swing.JLabel RegisterOrder_AddressLabel;
    private javax.swing.JButton RegisterOrder_BackButton;
    private javax.swing.JTextField RegisterOrder_CEPField;
    private javax.swing.JLabel RegisterOrder_CEPLabel;
    private javax.swing.JLabel RegisterOrder_DrinkLabel;
    private javax.swing.JLabel RegisterOrder_ItemLabel;
    private javax.swing.JScrollPane RegisterOrder_ItensList;
    private javax.swing.JList RegisterOrder_ItensList2;
    private javax.swing.JTextField RegisterOrder_NameField;
    private javax.swing.JLabel RegisterOrder_NameLabel;
    private javax.swing.JComboBox RegisterOrder_OutroField;
    private javax.swing.JTextField RegisterOrder_PhoneNumberField;
    private javax.swing.JLabel RegisterOrder_PhoneNumberLabel;
    private javax.swing.JLabel RegisterOrder_PizzaLabel;
    private javax.swing.JLabel RegisterOrder_PizzaTitle;
    private javax.swing.JTextField RegisterOrder_PriceField;
    private javax.swing.JButton RegisterOrder_RegisterOrderButton;
    private javax.swing.JButton RegisterOrder_RemoveItemButton;
    private javax.swing.JButton RegisterOrder_SearchClientButton;
    private javax.swing.JSeparator RegisterOrder_Separator;
    private javax.swing.JComboBox RegisterOrder_SizeField;
    private javax.swing.JLabel RegisterOrder_SizeLabel;
    private javax.swing.JComboBox RegisterOrder_TasteField1;
    private javax.swing.JComboBox RegisterOrder_TasteField2;
    private javax.swing.JComboBox RegisterOrder_TasteField3;
    private javax.swing.JLabel RegisterOrder_TasteLabel;
    private javax.swing.JLabel RegisterOrder_Title;
    private javax.swing.JButton RegisterOrder_UpdateClientButton;
    private javax.swing.JPanel RegisterPizza;
    private javax.swing.JButton RegisterPizza_BackButton;
    private javax.swing.JTextField RegisterPizza_OutroNameField;
    private javax.swing.JTextField RegisterPizza_OutroPriceField;
    private javax.swing.JTextField RegisterPizza_PriceFieldBig;
    private javax.swing.JTextField RegisterPizza_PriceFieldFamily;
    private javax.swing.JTextField RegisterPizza_PriceFieldMedium;
    private javax.swing.JButton RegisterPizza_RegisterPizzaButton;
    private javax.swing.JButton RegisterPizza_RegisterPizzaButton1;
    private javax.swing.JTextField RegisterPizza_TasteField;
    private javax.swing.JLabel RegisterPizza_TasteLabel;
    private javax.swing.JLabel RegisterPizza_TasteLabel1;
    private javax.swing.JLabel RegisterPizza_TasteLabel4;
    private javax.swing.JLabel RegisterPizza_TasteLabel5;
    private javax.swing.JLabel RegisterPizza_TasteLabel6;
    private javax.swing.JLabel RegisterPizza_TasteLabel7;
    private javax.swing.JLabel RegisterPizza_Title;
    private javax.swing.JLabel RegisterPizza_Title1;
    private javax.swing.JPanel RegisterUser;
    private javax.swing.JTextField RegisterUser_AddressField;
    private javax.swing.JLabel RegisterUser_AddressLabel;
    private javax.swing.JButton RegisterUser_BackButton;
    private javax.swing.JTextField RegisterUser_CEPField;
    private javax.swing.JLabel RegisterUser_CEPLabel;
    private javax.swing.JTextField RegisterUser_CPFField;
    private javax.swing.JLabel RegisterUser_CPFLabel;
    private javax.swing.JTextField RegisterUser_NameField;
    private javax.swing.JLabel RegisterUser_NameLabel;
    private javax.swing.JTextField RegisterUser_PasswordField;
    private javax.swing.JLabel RegisterUser_PasswordLabel;
    private javax.swing.JTextField RegisterUser_PhoneNumberField;
    private javax.swing.JLabel RegisterUser_PhoneNumberLabel;
    private javax.swing.JButton RegisterUser_RegisterUserButton;
    private javax.swing.JComboBox RegisterUser_RoleField;
    private javax.swing.JLabel RegisterUser_Title;
    private javax.swing.JLabel RegisterUser_TypeLabel;
    private javax.swing.JTextField RegisterUser_UserField;
    private javax.swing.JLabel RegisterUser_UserLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private Float setPizzaPrice() {
        Pizza pizza = new Pizza();
        pizza.setSize((Size) RegisterOrder_SizeField.getSelectedItem());
        pizza.setTaste1((String) RegisterOrder_TasteField1.getSelectedItem());
        pizza.setTaste2((String) RegisterOrder_TasteField2.getSelectedItem());
        pizza.setTaste3((String) RegisterOrder_TasteField3.getSelectedItem());
        Float price = 0f;
        try {
            price = Main.getPizzaria().calculatePizzaPrice(pizza);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha na comunicação com banco de dados");
        }
        RegisterOrder_PriceField.setText("R$" + String.valueOf(price));
        return price;
    }
}
