/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzasystem.ui;
import newpackage.businesslogic.Pizzaria;
import pizzasystem.data.Client;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author jools
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
     // para diferentes usuarios quando voltar a tela
    
    public MainFrame() {
        initComponents();
        MainJPanel.removeAll();
        MainJPanel.add(Login);
        MainJPanel.revalidate();
    }

    private int LoginPower = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainJPanel = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        LoginForm_Title = new javax.swing.JLabel();
        LoginForm_UsernameLabel = new javax.swing.JLabel();
        LoginForm_UsernameField = new javax.swing.JTextField();
        LoginForm_PasswordLabel = new javax.swing.JLabel();
        LoginForm_PasswordField = new javax.swing.JTextField();
        LoginForm_LoginButton = new javax.swing.JButton();
        Atendente = new javax.swing.JPanel();
        AtendenteForm_Name = new javax.swing.JLabel();
        AtendenteForm_Orders = new javax.swing.JScrollPane();
        Orders_Table1 = new javax.swing.JTable();
        AtendenteForm_OrdersLabel = new javax.swing.JLabel();
        AtendenteForm_Logout = new javax.swing.JButton();
        AtendenteForm_RegisterOrder = new javax.swing.JButton();
        AtendenteForm_RegisterClient = new javax.swing.JButton();
        Admin = new javax.swing.JPanel();
        AdminForm_Name = new javax.swing.JLabel();
        AdminForm_Orders = new javax.swing.JScrollPane();
        Orders_Table = new javax.swing.JTable();
        AdminForm_OrdersLabel = new javax.swing.JLabel();
        AdminForm_RegisterOrder = new javax.swing.JButton();
        AdminForm_RegisterClient = new javax.swing.JButton();
        AdminForm_RegisterUser = new javax.swing.JButton();
        AdminForm_RegisterPizza = new javax.swing.JButton();
        AdminForm_FinishPizza = new javax.swing.JButton();
        AdminForm_FinishOrder = new javax.swing.JButton();
        AdminForm_Logout = new javax.swing.JButton();
        Pizzaiolo = new javax.swing.JPanel();
        PizzaioloForm_Name = new javax.swing.JLabel();
        PizzaioloForm_Orders = new javax.swing.JScrollPane();
        Orders_Table2 = new javax.swing.JTable();
        PizzaioloForm_FinishPizza = new javax.swing.JButton();
        PizzaioloForm_Logout = new javax.swing.JButton();
        PizzaioloForm_OrdersLabel = new javax.swing.JLabel();
        Entregador = new javax.swing.JPanel();
        EntregadorForm_Name = new javax.swing.JLabel();
        EntregadorForm_Orders2 = new javax.swing.JScrollPane();
        Orders_Table3 = new javax.swing.JTable();
        EntregadorForm_FinishOrder = new javax.swing.JButton();
        EntregadorForm_Logout = new javax.swing.JButton();
        EntregadorForm_OrdersLabel = new javax.swing.JLabel();
        RegisterOrder = new javax.swing.JPanel();
        RegisterOrder_Title = new javax.swing.JLabel();
        RegisterOrder_PhoneNumberLabel = new javax.swing.JLabel();
        RegisterOrder_PhoneNumberField = new javax.swing.JTextField();
        RegisterOrder_NameLabel = new javax.swing.JLabel();
        RegisterOrder_NameField = new javax.swing.JTextField();
        RegisterOrder_AddressLabel = new javax.swing.JLabel();
        RegisterOrder_AddressField = new javax.swing.JTextField();
        RegisterOrder_CEPLabel = new javax.swing.JLabel();
        RegisterOrder_CEPField = new javax.swing.JTextField();
        RegisterOrder_Separator = new javax.swing.JSeparator();
        RegisterOrder_PizzaTitle = new javax.swing.JLabel();
        RegisterOrder_TasteLabel = new javax.swing.JLabel();
        RegisterOrder_SizeLabel = new javax.swing.JLabel();
        RegisterOrder_Taste = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        RegisterOrder_Size = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList();
        RegisterOrder_RegisterOrderButton = new javax.swing.JButton();
        RegisterOrder_SearchClientButton = new javax.swing.JButton();
        RegisterOrder_UpdateClientButton = new javax.swing.JButton();
        RegisterOrder_BackButton = new javax.swing.JButton();
        RegisterOrder_PizzaLabel = new javax.swing.JLabel();
        RegisterOrder_AddPizzaButton = new javax.swing.JButton();
        RegisterOrder_RemoveItemButton = new javax.swing.JButton();
        RegisterOrder_ItemLabel = new javax.swing.JLabel();
        RegisterOrder_ItensList = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList();
        RegisterOrder_DrinkLabel = new javax.swing.JLabel();
        RegisterOrder_DrinkList = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        RegisterOrder_AddDrinkButton = new javax.swing.JButton();
        RegisterClient = new javax.swing.JPanel();
        RegisterClient_Title = new javax.swing.JLabel();
        RegisterClient_PhoneNumberLabel = new javax.swing.JLabel();
        RegisterClient_PhoneNumberField = new javax.swing.JTextField();
        RegisterClient_NameLabel = new javax.swing.JLabel();
        RegisterClient_NameField = new javax.swing.JTextField();
        RegisterClient_AddressLabel = new javax.swing.JLabel();
        RegisterClient_AddressField = new javax.swing.JTextField();
        RegisterClient_CEPLabel = new javax.swing.JLabel();
        RegisterClient_CEPField = new javax.swing.JTextField();
        RegisterClient_RegisterClientButton = new javax.swing.JButton();
        RegisterClient_BackButton = new javax.swing.JButton();
        RegisterUser = new javax.swing.JPanel();
        RegisterUser_Title = new javax.swing.JLabel();
        RegisterUser_PhoneNumberLabel = new javax.swing.JLabel();
        RegisterUser_PhoneNumberField = new javax.swing.JTextField();
        RegisterUser_NameLabel = new javax.swing.JLabel();
        RegisterUser_NameField = new javax.swing.JTextField();
        RegisterUser_AddressLabel = new javax.swing.JLabel();
        RegisterUser_AddressField = new javax.swing.JTextField();
        RegisterUser_CEPLabel = new javax.swing.JLabel();
        RegisterUser_CEPField = new javax.swing.JTextField();
        RegisterUser_CPFLabel = new javax.swing.JLabel();
        RegisterUser_CPFFied = new javax.swing.JTextField();
        RegisterUser_UserLabel = new javax.swing.JLabel();
        RegisterUser_UserField = new javax.swing.JTextField();
        RegisterUser_PasswordLabel = new javax.swing.JLabel();
        RegisterUser_PasswordField = new javax.swing.JTextField();
        RegisterUser_TypeLabel = new javax.swing.JLabel();
        RegisterUser_TypeScrollPane = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList();
        RegisterUser_RegisterUserButton = new javax.swing.JButton();
        RegisterUser_BackButton = new javax.swing.JButton();
        RegisterPizza = new javax.swing.JPanel();
        RegisterPizza_Title = new javax.swing.JLabel();
        RegisterPizza_TasteLabel = new javax.swing.JLabel();
        RegisterPizza_TasteField = new javax.swing.JTextField();
        RegisterPizza_RegisterPizzaButton = new javax.swing.JButton();
        RegisterPizza_BackButton = new javax.swing.JButton();
        FinishPizza = new javax.swing.JPanel();
        FinishPizza_Title = new javax.swing.JLabel();
        FinishPizza_NumberLabel = new javax.swing.JLabel();
        FinishPizza_NumberField = new javax.swing.JTextField();
        FinishPizza_FinishPizzaButton = new javax.swing.JButton();
        FinishPizza_BackButton = new javax.swing.JButton();
        FinishOrder = new javax.swing.JPanel();
        FinishOrder_Title = new javax.swing.JLabel();
        FinishOrder_NumberLabel = new javax.swing.JLabel();
        FinishOrder_NumberField = new javax.swing.JTextField();
        FinishOrder_FinishOrderButton = new javax.swing.JButton();
        FinishOrder_BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainJPanel.setLayout(new java.awt.CardLayout());

        LoginForm_Title.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        LoginForm_Title.setText("Login");

        LoginForm_UsernameLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        LoginForm_UsernameLabel.setText("Usuário");

        LoginForm_UsernameField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        LoginForm_PasswordLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        LoginForm_PasswordLabel.setText("Senha");

        LoginForm_PasswordField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        LoginForm_LoginButton.setText("Login");
        LoginForm_LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginForm_LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginForm_LoginButton)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoginForm_UsernameLabel)
                            .addComponent(LoginForm_PasswordLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginForm_UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoginForm_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LoginForm_Title))
                .addContainerGap(550, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LoginForm_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginForm_UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginForm_UsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginForm_PasswordLabel)
                    .addComponent(LoginForm_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LoginForm_LoginButton)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        MainJPanel.add(Login, "card2");

        AtendenteForm_Name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        AtendenteForm_Name.setText("Atendente: Nome");

        Orders_Table1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Orders_Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Telefone", "Status", "Valor", "Endereço", "Pedido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AtendenteForm_Orders.setViewportView(Orders_Table1);

        AtendenteForm_OrdersLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        AtendenteForm_OrdersLabel.setText("Pedidos");

        AtendenteForm_Logout.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        AtendenteForm_Logout.setText("Deslogar");
        AtendenteForm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtendenteForm_LogoutActionPerformed(evt);
            }
        });

        AtendenteForm_RegisterOrder.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        AtendenteForm_RegisterOrder.setText("Cadastrar Pedido");
        AtendenteForm_RegisterOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtendenteForm_RegisterOrderActionPerformed(evt);
            }
        });

        AtendenteForm_RegisterClient.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        AtendenteForm_RegisterClient.setText("Cadastrar Cliente");
        AtendenteForm_RegisterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtendenteForm_RegisterClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AtendenteLayout = new javax.swing.GroupLayout(Atendente);
        Atendente.setLayout(AtendenteLayout);
        AtendenteLayout.setHorizontalGroup(
            AtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtendenteLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AtendenteForm_OrdersLabel)
                    .addComponent(AtendenteForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AtendenteLayout.createSequentialGroup()
                        .addComponent(AtendenteForm_RegisterOrder)
                        .addGap(18, 18, 18)
                        .addComponent(AtendenteForm_RegisterClient)
                        .addGap(18, 18, 18)
                        .addComponent(AtendenteForm_Logout))
                    .addComponent(AtendenteForm_Name))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        AtendenteLayout.setVerticalGroup(
            AtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtendenteLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(AtendenteForm_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtendenteForm_RegisterOrder)
                    .addComponent(AtendenteForm_RegisterClient)
                    .addComponent(AtendenteForm_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(AtendenteForm_OrdersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AtendenteForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainJPanel.add(Atendente, "card2");

        AdminForm_Name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        AdminForm_Name.setText("Administrador: Nome");

        Orders_Table.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Orders_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Telefone", "Status", "Valor", "Endereço", "Pedido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AdminForm_Orders.setViewportView(Orders_Table);

        AdminForm_OrdersLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        AdminForm_OrdersLabel.setText("Pedidos");

        AdminForm_RegisterOrder.setText("Cadastrar Pedido");
        AdminForm_RegisterOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_RegisterOrderActionPerformed(evt);
            }
        });

        AdminForm_RegisterClient.setText("Cadastrar Cliente");
        AdminForm_RegisterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_RegisterClientActionPerformed(evt);
            }
        });

        AdminForm_RegisterUser.setText("Cadastrar Usuário");
        AdminForm_RegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_RegisterUserActionPerformed(evt);
            }
        });

        AdminForm_RegisterPizza.setText("Cadastrar Pizza");
        AdminForm_RegisterPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_RegisterPizzaActionPerformed(evt);
            }
        });

        AdminForm_FinishPizza.setText("Finalizar Pizza");
        AdminForm_FinishPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_FinishPizzaActionPerformed(evt);
            }
        });

        AdminForm_FinishOrder.setText("Finalizar Entrega");
        AdminForm_FinishOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_FinishOrderActionPerformed(evt);
            }
        });

        AdminForm_Logout.setText("Deslogar");
        AdminForm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
        Admin.setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminForm_OrdersLabel)
                    .addComponent(AdminForm_Name)
                    .addComponent(AdminForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdminLayout.createSequentialGroup()
                        .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminForm_RegisterOrder)
                            .addComponent(AdminForm_FinishPizza))
                        .addGap(18, 18, 18)
                        .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminForm_FinishOrder)
                            .addGroup(AdminLayout.createSequentialGroup()
                                .addComponent(AdminForm_RegisterClient)
                                .addGap(18, 18, 18)
                                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AdminForm_Logout)
                                    .addGroup(AdminLayout.createSequentialGroup()
                                        .addComponent(AdminForm_RegisterUser)
                                        .addGap(18, 18, 18)
                                        .addComponent(AdminForm_RegisterPizza)))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(AdminForm_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminForm_RegisterOrder)
                    .addComponent(AdminForm_RegisterClient)
                    .addComponent(AdminForm_RegisterUser)
                    .addComponent(AdminForm_RegisterPizza))
                .addGap(18, 18, 18)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminForm_FinishPizza)
                    .addComponent(AdminForm_FinishOrder)
                    .addComponent(AdminForm_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(AdminForm_OrdersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainJPanel.add(Admin, "card2");

        PizzaioloForm_Name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        PizzaioloForm_Name.setText("Pizzaiolo: Nome");

        Orders_Table2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Orders_Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Número", "Pedido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PizzaioloForm_Orders.setViewportView(Orders_Table2);

        PizzaioloForm_FinishPizza.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        PizzaioloForm_FinishPizza.setText("Finalizar Pizza");
        PizzaioloForm_FinishPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaioloForm_FinishPizzaActionPerformed(evt);
            }
        });

        PizzaioloForm_Logout.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        PizzaioloForm_Logout.setText("Deslogar");
        PizzaioloForm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaioloForm_LogoutActionPerformed(evt);
            }
        });

        PizzaioloForm_OrdersLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        PizzaioloForm_OrdersLabel.setText("Pedidos");

        javax.swing.GroupLayout PizzaioloLayout = new javax.swing.GroupLayout(Pizzaiolo);
        Pizzaiolo.setLayout(PizzaioloLayout);
        PizzaioloLayout.setHorizontalGroup(
            PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PizzaioloLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PizzaioloForm_OrdersLabel)
                    .addGroup(PizzaioloLayout.createSequentialGroup()
                        .addComponent(PizzaioloForm_FinishPizza)
                        .addGap(18, 18, 18)
                        .addComponent(PizzaioloForm_Logout))
                    .addComponent(PizzaioloForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PizzaioloForm_Name))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PizzaioloLayout.setVerticalGroup(
            PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PizzaioloLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(PizzaioloForm_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PizzaioloForm_FinishPizza)
                    .addComponent(PizzaioloForm_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(PizzaioloForm_OrdersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PizzaioloForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainJPanel.add(Pizzaiolo, "card2");

        EntregadorForm_Name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        EntregadorForm_Name.setText("Entregador: Nome");

        Orders_Table3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Orders_Table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Telefone", "Status", "Valor", "Endereço", "Pedido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EntregadorForm_Orders2.setViewportView(Orders_Table3);

        EntregadorForm_FinishOrder.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        EntregadorForm_FinishOrder.setText("Finalizar Entrega");
        EntregadorForm_FinishOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntregadorForm_FinishOrderActionPerformed(evt);
            }
        });

        EntregadorForm_Logout.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        EntregadorForm_Logout.setText("Deslogar");
        EntregadorForm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntregadorForm_LogoutActionPerformed(evt);
            }
        });

        EntregadorForm_OrdersLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        EntregadorForm_OrdersLabel.setText("Pedidos");

        javax.swing.GroupLayout EntregadorLayout = new javax.swing.GroupLayout(Entregador);
        Entregador.setLayout(EntregadorLayout);
        EntregadorLayout.setHorizontalGroup(
            EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntregadorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EntregadorForm_OrdersLabel)
                    .addGroup(EntregadorLayout.createSequentialGroup()
                        .addComponent(EntregadorForm_FinishOrder)
                        .addGap(18, 18, 18)
                        .addComponent(EntregadorForm_Logout))
                    .addComponent(EntregadorForm_Orders2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntregadorForm_Name))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        EntregadorLayout.setVerticalGroup(
            EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntregadorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(EntregadorForm_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntregadorForm_FinishOrder)
                    .addComponent(EntregadorForm_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(EntregadorForm_OrdersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EntregadorForm_Orders2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainJPanel.add(Entregador, "card2");

        RegisterOrder_Title.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        RegisterOrder_Title.setText("Registrar Pedido");

        RegisterOrder_PhoneNumberLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RegisterOrder_PhoneNumberLabel.setText("Telefone");

        RegisterOrder_PhoneNumberField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RegisterOrder_PhoneNumberField.setToolTipText("");

        RegisterOrder_NameLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RegisterOrder_NameLabel.setText("Nome");

        RegisterOrder_NameField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        RegisterOrder_AddressLabel.setText("Endereço");

        RegisterOrder_CEPLabel.setText("CEP");

        RegisterOrder_PizzaTitle.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        RegisterOrder_PizzaTitle.setText("Pedido");

        RegisterOrder_TasteLabel.setText("Sabores");

        RegisterOrder_SizeLabel.setText("Tamanho");

        RegisterOrder_Taste.setViewportView(jList1);

        jList6.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Família", "Grande", "Média" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList6.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        RegisterOrder_Size.setViewportView(jList6);

        RegisterOrder_RegisterOrderButton.setText("Realizar Pedido");

        RegisterOrder_SearchClientButton.setText("Procurar");
        RegisterOrder_SearchClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_SearchClientButtonActionPerformed(evt);
            }
        });

        RegisterOrder_UpdateClientButton.setText("Atualizar ou Registrar Novo Cliente");
        RegisterOrder_UpdateClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_UpdateClientButtonActionPerformed(evt);
            }
        });

        RegisterOrder_BackButton.setText("Voltar");
        RegisterOrder_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterOrder_BackButtonActionPerformed(evt);
            }
        });

        RegisterOrder_PizzaLabel.setText("Pizza");

        RegisterOrder_AddPizzaButton.setText("Adicionar");

        RegisterOrder_RemoveItemButton.setText("Remover");

        RegisterOrder_ItemLabel.setText("Itens");

        RegisterOrder_ItensList.setViewportView(jList8);

        RegisterOrder_DrinkLabel.setText("Bebidas");

        RegisterOrder_DrinkList.setViewportView(jList2);

        RegisterOrder_AddDrinkButton.setText("Adicionar");

        javax.swing.GroupLayout RegisterOrderLayout = new javax.swing.GroupLayout(RegisterOrder);
        RegisterOrder.setLayout(RegisterOrderLayout);
        RegisterOrderLayout.setHorizontalGroup(
            RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterOrderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegisterOrder_NameLabel)
                            .addComponent(RegisterOrder_PhoneNumberLabel)
                            .addComponent(RegisterOrder_AddressLabel)
                            .addComponent(RegisterOrder_CEPLabel))
                        .addGap(18, 18, 18)
                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterOrderLayout.createSequentialGroup()
                                .addComponent(RegisterOrder_PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(RegisterOrder_SearchClientButton)
                                .addGap(18, 18, 18)
                                .addComponent(RegisterOrder_UpdateClientButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RegisterOrder_BackButton))
                            .addComponent(RegisterOrder_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterOrder_AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterOrder_CEPField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                        .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterOrderLayout.createSequentialGroup()
                                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                                        .addComponent(RegisterOrder_AddPizzaButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RegisterOrder_RemoveItemButton))
                                    .addComponent(RegisterOrder_PizzaLabel))
                                .addGap(122, 122, 122)
                                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisterOrder_ItemLabel)
                                    .addComponent(RegisterOrder_RegisterOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addComponent(RegisterOrder_DrinkLabel))
                            .addComponent(RegisterOrder_PizzaTitle)
                            .addComponent(RegisterOrder_Title)
                            .addComponent(RegisterOrder_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegisterOrderLayout.createSequentialGroup()
                                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                                        .addComponent(RegisterOrder_SizeLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(RegisterOrder_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                                        .addComponent(RegisterOrder_TasteLabel)
                                        .addGap(23, 23, 23)
                                        .addComponent(RegisterOrder_Taste, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)
                                .addComponent(RegisterOrder_ItensList, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisterOrder_DrinkList, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterOrder_AddDrinkButton))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        RegisterOrderLayout.setVerticalGroup(
            RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterOrderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(RegisterOrder_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterOrder_PhoneNumberLabel)
                    .addComponent(RegisterOrder_PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterOrder_SearchClientButton)
                    .addComponent(RegisterOrder_UpdateClientButton)
                    .addComponent(RegisterOrder_BackButton))
                .addGap(18, 18, 18)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterOrder_NameLabel)
                    .addComponent(RegisterOrder_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterOrder_AddressLabel)
                    .addComponent(RegisterOrder_AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterOrder_CEPLabel)
                    .addComponent(RegisterOrder_CEPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterOrder_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterOrder_PizzaTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterOrder_PizzaLabel)
                    .addComponent(RegisterOrder_ItemLabel)
                    .addComponent(RegisterOrder_DrinkLabel))
                .addGap(21, 21, 21)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(RegisterOrder_TasteLabel)
                        .addGroup(RegisterOrderLayout.createSequentialGroup()
                            .addComponent(RegisterOrder_Taste, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RegisterOrder_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RegisterOrder_SizeLabel)))
                        .addComponent(RegisterOrder_ItensList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(RegisterOrderLayout.createSequentialGroup()
                        .addComponent(RegisterOrder_DrinkList, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegisterOrder_AddDrinkButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(RegisterOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterOrder_AddPizzaButton)
                    .addComponent(RegisterOrder_RemoveItemButton)
                    .addComponent(RegisterOrder_RegisterOrderButton))
                .addGap(55, 55, 55))
        );

        MainJPanel.add(RegisterOrder, "card2");

        RegisterClient_Title.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        RegisterClient_Title.setText("Registrar Cliente");

        RegisterClient_PhoneNumberLabel.setText("Telefone");

        RegisterClient_NameLabel.setText("Nome");

        RegisterClient_AddressLabel.setText("Endereço");

        RegisterClient_CEPLabel.setText("CEP");

        RegisterClient_RegisterClientButton.setText("Registrar Novo Cliente");

        RegisterClient_BackButton.setText("Voltar");
        RegisterClient_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterClient_BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterClientLayout = new javax.swing.GroupLayout(RegisterClient);
        RegisterClient.setLayout(RegisterClientLayout);
        RegisterClientLayout.setHorizontalGroup(
            RegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterClientLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterClientLayout.createSequentialGroup()
                        .addGroup(RegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegisterClientLayout.createSequentialGroup()
                                .addGroup(RegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RegisterClient_NameLabel)
                                    .addComponent(RegisterClient_PhoneNumberLabel)
                                    .addComponent(RegisterClient_AddressLabel)
                                    .addComponent(RegisterClient_CEPLabel))
                                .addGap(18, 18, 18)
                                .addGroup(RegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisterClient_PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterClient_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterClient_AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterClient_CEPField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(RegisterClient_RegisterClientButton))
                        .addContainerGap(397, Short.MAX_VALUE))
                    .addGroup(RegisterClientLayout.createSequentialGroup()
                        .addComponent(RegisterClient_Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RegisterClient_BackButton)
                        .addGap(40, 40, 40))))
        );
        RegisterClientLayout.setVerticalGroup(
            RegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterClientLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterClient_Title)
                    .addComponent(RegisterClient_BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterClient_PhoneNumberLabel)
                    .addComponent(RegisterClient_PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterClient_NameLabel)
                    .addComponent(RegisterClient_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterClient_AddressLabel)
                    .addComponent(RegisterClient_AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterClient_CEPLabel)
                    .addComponent(RegisterClient_CEPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RegisterClient_RegisterClientButton)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        MainJPanel.add(RegisterClient, "card2");

        RegisterUser_Title.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        RegisterUser_Title.setText("Registrar Usuário");

        RegisterUser_PhoneNumberLabel.setText("Telefone");

        RegisterUser_NameLabel.setText("Nome");

        RegisterUser_AddressLabel.setText("Endereço");

        RegisterUser_CEPLabel.setText("CEP");

        RegisterUser_CPFLabel.setText("CPF");

        RegisterUser_UserLabel.setText("Usuário");

        RegisterUser_PasswordLabel.setText("Senha");

        RegisterUser_TypeLabel.setText("Tipo");

        jList7.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Administrador", "Atendente", "Pizzaiolo", "Entregador" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList7.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        RegisterUser_TypeScrollPane.setViewportView(jList7);

        RegisterUser_RegisterUserButton.setText("Registrar Novo Usuário");

        RegisterUser_BackButton.setText("Voltar");
        RegisterUser_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUser_BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterUserLayout = new javax.swing.GroupLayout(RegisterUser);
        RegisterUser.setLayout(RegisterUserLayout);
        RegisterUserLayout.setHorizontalGroup(
            RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterUserLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterUser_Title)
                    .addGroup(RegisterUserLayout.createSequentialGroup()
                        .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegisterUser_NameLabel)
                            .addComponent(RegisterUser_PhoneNumberLabel)
                            .addComponent(RegisterUser_AddressLabel)
                            .addComponent(RegisterUser_CEPLabel)
                            .addComponent(RegisterUser_CPFLabel))
                        .addGap(18, 18, 18)
                        .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterUser_AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterUser_CPFFied, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegisterUserLayout.createSequentialGroup()
                                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisterUser_PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterUser_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterUser_CEPField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(171, 171, 171)
                                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisterUser_UserLabel)
                                    .addComponent(RegisterUser_PasswordLabel)
                                    .addComponent(RegisterUser_TypeLabel))
                                .addGap(18, 18, 18)
                                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisterUser_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterUser_TypeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RegisterUserLayout.createSequentialGroup()
                                        .addComponent(RegisterUser_UserField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                                        .addComponent(RegisterUser_BackButton))))))
                    .addComponent(RegisterUser_RegisterUserButton))
                .addGap(40, 40, 40))
        );
        RegisterUserLayout.setVerticalGroup(
            RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterUserLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterUserLayout.createSequentialGroup()
                        .addComponent(RegisterUser_Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterUser_PhoneNumberLabel)
                            .addComponent(RegisterUser_PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterUser_UserLabel)
                            .addComponent(RegisterUser_UserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(RegisterUser_BackButton))
                .addGap(18, 18, 18)
                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterUser_NameLabel)
                    .addComponent(RegisterUser_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterUser_PasswordLabel)
                    .addComponent(RegisterUser_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterUser_AddressLabel)
                    .addComponent(RegisterUser_AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(RegisterUserLayout.createSequentialGroup()
                        .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterUser_CEPLabel)
                            .addComponent(RegisterUser_CEPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterUser_TypeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(RegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterUser_CPFLabel)
                            .addComponent(RegisterUser_CPFFied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(RegisterUser_TypeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(RegisterUser_RegisterUserButton)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        MainJPanel.add(RegisterUser, "card2");

        RegisterPizza_Title.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        RegisterPizza_Title.setText("Registrar Pizza");

        RegisterPizza_TasteLabel.setText("Sabor");

        RegisterPizza_RegisterPizzaButton.setText("Registrar Nova Pizza");

        RegisterPizza_BackButton.setText("Voltar");
        RegisterPizza_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPizza_BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterPizzaLayout = new javax.swing.GroupLayout(RegisterPizza);
        RegisterPizza.setLayout(RegisterPizzaLayout);
        RegisterPizzaLayout.setHorizontalGroup(
            RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPizzaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterPizzaLayout.createSequentialGroup()
                        .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterPizza_RegisterPizzaButton)
                            .addGroup(RegisterPizzaLayout.createSequentialGroup()
                                .addComponent(RegisterPizza_TasteLabel)
                                .addGap(18, 18, 18)
                                .addComponent(RegisterPizza_TasteField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RegisterPizzaLayout.createSequentialGroup()
                        .addComponent(RegisterPizza_Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                        .addComponent(RegisterPizza_BackButton)
                        .addGap(40, 40, 40))))
        );
        RegisterPizzaLayout.setVerticalGroup(
            RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPizzaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterPizza_Title)
                    .addComponent(RegisterPizza_BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterPizza_TasteLabel)
                    .addComponent(RegisterPizza_TasteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterPizza_RegisterPizzaButton)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        MainJPanel.add(RegisterPizza, "card2");

        FinishPizza_Title.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        FinishPizza_Title.setText("Finalizar Pizza");

        FinishPizza_NumberLabel.setText("Número");

        FinishPizza_FinishPizzaButton.setText("Finalizar Pizza");

        FinishPizza_BackButton.setText("Voltar");
        FinishPizza_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishPizza_BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FinishPizzaLayout = new javax.swing.GroupLayout(FinishPizza);
        FinishPizza.setLayout(FinishPizzaLayout);
        FinishPizzaLayout.setHorizontalGroup(
            FinishPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinishPizzaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(FinishPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FinishPizzaLayout.createSequentialGroup()
                        .addGroup(FinishPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FinishPizza_FinishPizzaButton)
                            .addGroup(FinishPizzaLayout.createSequentialGroup()
                                .addComponent(FinishPizza_NumberLabel)
                                .addGap(18, 18, 18)
                                .addComponent(FinishPizza_NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(555, Short.MAX_VALUE))
                    .addGroup(FinishPizzaLayout.createSequentialGroup()
                        .addComponent(FinishPizza_Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FinishPizza_BackButton)
                        .addGap(40, 40, 40))))
        );
        FinishPizzaLayout.setVerticalGroup(
            FinishPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinishPizzaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(FinishPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FinishPizza_Title)
                    .addComponent(FinishPizza_BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FinishPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinishPizza_NumberLabel)
                    .addComponent(FinishPizza_NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FinishPizza_FinishPizzaButton)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        MainJPanel.add(FinishPizza, "card2");

        FinishOrder_Title.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        FinishOrder_Title.setText("Finalizar Pedido");

        FinishOrder_NumberLabel.setText("Número");

        FinishOrder_FinishOrderButton.setText("Finalizar Pedido");

        FinishOrder_BackButton.setText("Voltar");
        FinishOrder_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishOrder_BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FinishOrderLayout = new javax.swing.GroupLayout(FinishOrder);
        FinishOrder.setLayout(FinishOrderLayout);
        FinishOrderLayout.setHorizontalGroup(
            FinishOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinishOrderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(FinishOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FinishOrderLayout.createSequentialGroup()
                        .addGroup(FinishOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FinishOrder_FinishOrderButton)
                            .addGroup(FinishOrderLayout.createSequentialGroup()
                                .addComponent(FinishOrder_NumberLabel)
                                .addGap(18, 18, 18)
                                .addComponent(FinishOrder_NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(555, Short.MAX_VALUE))
                    .addGroup(FinishOrderLayout.createSequentialGroup()
                        .addComponent(FinishOrder_Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FinishOrder_BackButton)
                        .addGap(40, 40, 40))))
        );
        FinishOrderLayout.setVerticalGroup(
            FinishOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinishOrderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(FinishOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FinishOrder_Title)
                    .addComponent(FinishOrder_BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FinishOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinishOrder_NumberLabel)
                    .addComponent(FinishOrder_NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FinishOrder_FinishOrderButton)
                .addContainerGap(380, Short.MAX_VALUE))
        );

        MainJPanel.add(FinishOrder, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginForm_LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginForm_LoginButtonActionPerformed
        // TODO add your handling code here:

        //if(this.Login()) { // sistema de login aqui
        if(true) { 
            MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();
            
            MainJPanel.add(Admin);
            MainJPanel.repaint();
            MainJPanel.revalidate();
        }

    }//GEN-LAST:event_LoginForm_LoginButtonActionPerformed

    private void AtendenteForm_RegisterOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtendenteForm_RegisterOrderActionPerformed
        // TODO add your handling code here:
        this.RegisterOrder();
    }//GEN-LAST:event_AtendenteForm_RegisterOrderActionPerformed

    private void AtendenteForm_RegisterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtendenteForm_RegisterClientActionPerformed
        // TODO add your handling code here:
        this.RegisterClient();
    }//GEN-LAST:event_AtendenteForm_RegisterClientActionPerformed

    private void AtendenteForm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtendenteForm_LogoutActionPerformed
        // TODO add your handling code here:
        this.Logout();
    }//GEN-LAST:event_AtendenteForm_LogoutActionPerformed

    private void AdminForm_RegisterOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_RegisterOrderActionPerformed
        // TODO add your handling code here:
        this.RegisterOrder();
    }//GEN-LAST:event_AdminForm_RegisterOrderActionPerformed

    private void AdminForm_RegisterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_RegisterClientActionPerformed
        // TODO add your handling code here:
        this.RegisterClient();
    }//GEN-LAST:event_AdminForm_RegisterClientActionPerformed

    private void AdminForm_RegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_RegisterUserActionPerformed
        // TODO add your handling code here:
        this.RegisterUser();
    }//GEN-LAST:event_AdminForm_RegisterUserActionPerformed

    private void AdminForm_RegisterPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_RegisterPizzaActionPerformed
        // TODO add your handling code here:
        this.RegisterPizza();
    }//GEN-LAST:event_AdminForm_RegisterPizzaActionPerformed

    private void AdminForm_FinishPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_FinishPizzaActionPerformed
        // TODO add your handling code here:
        this.FinishPizza();
    }//GEN-LAST:event_AdminForm_FinishPizzaActionPerformed

    private void AdminForm_FinishOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_FinishOrderActionPerformed
        // TODO add your handling code here:
        this.FinishOrder();
    }//GEN-LAST:event_AdminForm_FinishOrderActionPerformed

    private void AdminForm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminForm_LogoutActionPerformed
        // TODO add your handling code here:
        this.Logout();
    }//GEN-LAST:event_AdminForm_LogoutActionPerformed

    private void PizzaioloForm_FinishPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaioloForm_FinishPizzaActionPerformed
        // TODO add your handling code here:
        this.FinishPizza();
    }//GEN-LAST:event_PizzaioloForm_FinishPizzaActionPerformed

    private void PizzaioloForm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaioloForm_LogoutActionPerformed
        // TODO add your handling code here:
        this.Logout();
    }//GEN-LAST:event_PizzaioloForm_LogoutActionPerformed

    private void EntregadorForm_FinishOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntregadorForm_FinishOrderActionPerformed
        // TODO add your handling code here:
        this.FinishOrder();
    }//GEN-LAST:event_EntregadorForm_FinishOrderActionPerformed

    private void EntregadorForm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntregadorForm_LogoutActionPerformed
        // TODO add your handling code here:
        this.Logout();
    }//GEN-LAST:event_EntregadorForm_LogoutActionPerformed

    private void RegisterOrder_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_BackButtonActionPerformed
        // TODO add your handling code here:
        this.GoBack();
    }//GEN-LAST:event_RegisterOrder_BackButtonActionPerformed

    private void RegisterClient_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterClient_BackButtonActionPerformed
        // TODO add your handling code here:
        this.GoBack();
    }//GEN-LAST:event_RegisterClient_BackButtonActionPerformed

    private void RegisterUser_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUser_BackButtonActionPerformed
        // TODO add your handling code here:
        this.GoBack();
    }//GEN-LAST:event_RegisterUser_BackButtonActionPerformed

    private void RegisterPizza_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPizza_BackButtonActionPerformed
        // TODO add your handling code here:
        this.GoBack();
    }//GEN-LAST:event_RegisterPizza_BackButtonActionPerformed

    private void FinishPizza_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishPizza_BackButtonActionPerformed
        // TODO add your handling code here:
        this.GoBack();
    }//GEN-LAST:event_FinishPizza_BackButtonActionPerformed

    private void FinishOrder_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishOrder_BackButtonActionPerformed
        // TODO add your handling code here:
        this.GoBack();
    }//GEN-LAST:event_FinishOrder_BackButtonActionPerformed

    private void RegisterOrder_SearchClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_SearchClientButtonActionPerformed
        String number = (RegisterOrder_PhoneNumberField.getText());
        Client client = Pizzaria.findClient(number);
        RegisterOrder_AddressField.setText(client.getAddress());
        RegisterOrder_CEPField.setText(client.getCep());
        RegisterOrder_NameField.setText(client.getName()); 
    }//GEN-LAST:event_RegisterOrder_SearchClientButtonActionPerformed

    private void RegisterOrder_UpdateClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterOrder_UpdateClientButtonActionPerformed

        Client clienttoadd = new Client();
        clienttoadd.setAddress(RegisterOrder_AddressField.getText());
        clienttoadd.setCep(RegisterOrder_CEPField.getText());
        clienttoadd.setName(RegisterOrder_NameField.getText());
        clienttoadd.setPhoneNumber(RegisterOrder_PhoneNumberField.getText());
        Pizzaria.addClient(clienttoadd);    
    }//GEN-LAST:event_RegisterOrder_UpdateClientButtonActionPerformed

    private void RegisterOrder() {
        MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();
            
            MainJPanel.add(RegisterOrder);
            MainJPanel.repaint();
            MainJPanel.revalidate();
    }
    
    private void RegisterClient() {
        MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();
            
            MainJPanel.add(RegisterClient);
            MainJPanel.repaint();
            MainJPanel.revalidate();
    }
    
    private void RegisterUser() {
        MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();
            
            MainJPanel.add(RegisterUser);
            MainJPanel.repaint();
            MainJPanel.revalidate();
    }
    
    private void RegisterPizza() {
        MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();
            
            MainJPanel.add(RegisterPizza);
            MainJPanel.repaint();
            MainJPanel.revalidate();
    }
    
    private void FinishPizza() {
        MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();
            
            MainJPanel.add(FinishPizza);
            MainJPanel.repaint();
            MainJPanel.revalidate();
    }
    
    private void FinishOrder() {
        MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();
            
            MainJPanel.add(FinishOrder);
            MainJPanel.repaint();
            MainJPanel.revalidate();
    }
    
    private void Logout() {
        MainJPanel.removeAll();
            MainJPanel.repaint();
            MainJPanel.revalidate();
            
            MainJPanel.add(Login);
            MainJPanel.repaint();
            MainJPanel.revalidate();
    }
    
    private void Login() {
        
    }
    
    private void GoBack() {
        switch(this.LoginPower) {
            case 1: // admin
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();

                MainJPanel.add(Admin);
                MainJPanel.repaint();
                MainJPanel.revalidate();
                break;
            case 2: // atendente
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();

                MainJPanel.add(Atendente);
                MainJPanel.repaint();
                MainJPanel.revalidate();
                break;
            case 3: // pizzaiolo
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();

                MainJPanel.add(Pizzaiolo);
                MainJPanel.repaint();
                MainJPanel.revalidate();
                break;
            case 4: // entregador
                MainJPanel.removeAll();
                MainJPanel.repaint();
                MainJPanel.revalidate();

                MainJPanel.add(Entregador);
                MainJPanel.repaint();
                MainJPanel.revalidate();
                break;
            default: // outros(teste/error)
                this.Logout();
                break;
                
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    private javax.swing.JButton AdminForm_FinishOrder;
    private javax.swing.JButton AdminForm_FinishPizza;
    private javax.swing.JButton AdminForm_Logout;
    private javax.swing.JLabel AdminForm_Name;
    private javax.swing.JScrollPane AdminForm_Orders;
    private javax.swing.JLabel AdminForm_OrdersLabel;
    private javax.swing.JButton AdminForm_RegisterClient;
    private javax.swing.JButton AdminForm_RegisterOrder;
    private javax.swing.JButton AdminForm_RegisterPizza;
    private javax.swing.JButton AdminForm_RegisterUser;
    private javax.swing.JPanel Atendente;
    private javax.swing.JButton AtendenteForm_Logout;
    private javax.swing.JLabel AtendenteForm_Name;
    private javax.swing.JScrollPane AtendenteForm_Orders;
    private javax.swing.JLabel AtendenteForm_OrdersLabel;
    private javax.swing.JButton AtendenteForm_RegisterClient;
    private javax.swing.JButton AtendenteForm_RegisterOrder;
    private javax.swing.JPanel Entregador;
    private javax.swing.JButton EntregadorForm_FinishOrder;
    private javax.swing.JButton EntregadorForm_Logout;
    private javax.swing.JLabel EntregadorForm_Name;
    private javax.swing.JScrollPane EntregadorForm_Orders2;
    private javax.swing.JLabel EntregadorForm_OrdersLabel;
    private javax.swing.JPanel FinishOrder;
    private javax.swing.JButton FinishOrder_BackButton;
    private javax.swing.JButton FinishOrder_FinishOrderButton;
    private javax.swing.JTextField FinishOrder_NumberField;
    private javax.swing.JLabel FinishOrder_NumberLabel;
    private javax.swing.JLabel FinishOrder_Title;
    private javax.swing.JPanel FinishPizza;
    private javax.swing.JButton FinishPizza_BackButton;
    private javax.swing.JButton FinishPizza_FinishPizzaButton;
    private javax.swing.JTextField FinishPizza_NumberField;
    private javax.swing.JLabel FinishPizza_NumberLabel;
    private javax.swing.JLabel FinishPizza_Title;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginForm_LoginButton;
    private javax.swing.JTextField LoginForm_PasswordField;
    private javax.swing.JLabel LoginForm_PasswordLabel;
    private javax.swing.JLabel LoginForm_Title;
    private javax.swing.JTextField LoginForm_UsernameField;
    private javax.swing.JLabel LoginForm_UsernameLabel;
    private javax.swing.JPanel MainJPanel;
    private javax.swing.JTable Orders_Table;
    private javax.swing.JTable Orders_Table1;
    private javax.swing.JTable Orders_Table2;
    private javax.swing.JTable Orders_Table3;
    private javax.swing.JPanel Pizzaiolo;
    private javax.swing.JButton PizzaioloForm_FinishPizza;
    private javax.swing.JButton PizzaioloForm_Logout;
    private javax.swing.JLabel PizzaioloForm_Name;
    private javax.swing.JScrollPane PizzaioloForm_Orders;
    private javax.swing.JLabel PizzaioloForm_OrdersLabel;
    private javax.swing.JPanel RegisterClient;
    private javax.swing.JTextField RegisterClient_AddressField;
    private javax.swing.JLabel RegisterClient_AddressLabel;
    private javax.swing.JButton RegisterClient_BackButton;
    private javax.swing.JTextField RegisterClient_CEPField;
    private javax.swing.JLabel RegisterClient_CEPLabel;
    private javax.swing.JTextField RegisterClient_NameField;
    private javax.swing.JLabel RegisterClient_NameLabel;
    private javax.swing.JTextField RegisterClient_PhoneNumberField;
    private javax.swing.JLabel RegisterClient_PhoneNumberLabel;
    private javax.swing.JButton RegisterClient_RegisterClientButton;
    private javax.swing.JLabel RegisterClient_Title;
    private javax.swing.JPanel RegisterOrder;
    private javax.swing.JButton RegisterOrder_AddDrinkButton;
    private javax.swing.JButton RegisterOrder_AddPizzaButton;
    private javax.swing.JTextField RegisterOrder_AddressField;
    private javax.swing.JLabel RegisterOrder_AddressLabel;
    private javax.swing.JButton RegisterOrder_BackButton;
    private javax.swing.JTextField RegisterOrder_CEPField;
    private javax.swing.JLabel RegisterOrder_CEPLabel;
    private javax.swing.JLabel RegisterOrder_DrinkLabel;
    private javax.swing.JScrollPane RegisterOrder_DrinkList;
    private javax.swing.JLabel RegisterOrder_ItemLabel;
    private javax.swing.JScrollPane RegisterOrder_ItensList;
    private javax.swing.JTextField RegisterOrder_NameField;
    private javax.swing.JLabel RegisterOrder_NameLabel;
    private javax.swing.JTextField RegisterOrder_PhoneNumberField;
    private javax.swing.JLabel RegisterOrder_PhoneNumberLabel;
    private javax.swing.JLabel RegisterOrder_PizzaLabel;
    private javax.swing.JLabel RegisterOrder_PizzaTitle;
    private javax.swing.JButton RegisterOrder_RegisterOrderButton;
    private javax.swing.JButton RegisterOrder_RemoveItemButton;
    private javax.swing.JButton RegisterOrder_SearchClientButton;
    private javax.swing.JSeparator RegisterOrder_Separator;
    private javax.swing.JScrollPane RegisterOrder_Size;
    private javax.swing.JLabel RegisterOrder_SizeLabel;
    private javax.swing.JScrollPane RegisterOrder_Taste;
    private javax.swing.JLabel RegisterOrder_TasteLabel;
    private javax.swing.JLabel RegisterOrder_Title;
    private javax.swing.JButton RegisterOrder_UpdateClientButton;
    private javax.swing.JPanel RegisterPizza;
    private javax.swing.JButton RegisterPizza_BackButton;
    private javax.swing.JButton RegisterPizza_RegisterPizzaButton;
    private javax.swing.JTextField RegisterPizza_TasteField;
    private javax.swing.JLabel RegisterPizza_TasteLabel;
    private javax.swing.JLabel RegisterPizza_Title;
    private javax.swing.JPanel RegisterUser;
    private javax.swing.JTextField RegisterUser_AddressField;
    private javax.swing.JLabel RegisterUser_AddressLabel;
    private javax.swing.JButton RegisterUser_BackButton;
    private javax.swing.JTextField RegisterUser_CEPField;
    private javax.swing.JLabel RegisterUser_CEPLabel;
    private javax.swing.JTextField RegisterUser_CPFFied;
    private javax.swing.JLabel RegisterUser_CPFLabel;
    private javax.swing.JTextField RegisterUser_NameField;
    private javax.swing.JLabel RegisterUser_NameLabel;
    private javax.swing.JTextField RegisterUser_PasswordField;
    private javax.swing.JLabel RegisterUser_PasswordLabel;
    private javax.swing.JTextField RegisterUser_PhoneNumberField;
    private javax.swing.JLabel RegisterUser_PhoneNumberLabel;
    private javax.swing.JButton RegisterUser_RegisterUserButton;
    private javax.swing.JLabel RegisterUser_Title;
    private javax.swing.JLabel RegisterUser_TypeLabel;
    private javax.swing.JScrollPane RegisterUser_TypeScrollPane;
    private javax.swing.JTextField RegisterUser_UserField;
    private javax.swing.JLabel RegisterUser_UserLabel;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList6;
    private javax.swing.JList jList7;
    private javax.swing.JList jList8;
    // End of variables declaration//GEN-END:variables
}
