/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzasystem.ui;

/**
 *
 * @author jools
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        MainJPanel.removeAll();
        MainJPanel.add(Login);
        MainJPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        MainJPanel = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        LoginForm_Title = new javax.swing.JLabel();
        LoginForm_UsernameLabel = new javax.swing.JLabel();
        LoginForm_UsernameField = new javax.swing.JTextField();
        LoginForm_PasswordLabel = new javax.swing.JLabel();
        LoginForm_PasswordField = new javax.swing.JTextField();
        LoginForm_LoginButton = new javax.swing.JButton();
        Atendente = new javax.swing.JPanel();
        AtendenteForm_Name = new javax.swing.JLabel();
        AtendenteForm_Orders = new javax.swing.JScrollPane();
        Orders_Table1 = new javax.swing.JTable();
        AtendenteForm_OrdersLabel = new javax.swing.JLabel();
        AtendenteForm_Logout = new javax.swing.JButton();
        AtendenteForm_RegisterOrder = new javax.swing.JButton();
        AtendenteForm_RegisterClient = new javax.swing.JButton();
        Admin = new javax.swing.JPanel();
        AdminForm_Name = new javax.swing.JLabel();
        AdminForm_Orders = new javax.swing.JScrollPane();
        Orders_Table = new javax.swing.JTable();
        AdminForm_OrdersLabel = new javax.swing.JLabel();
        AdminForm_RegisterOrder = new javax.swing.JButton();
        AdminForm_RegisterClient = new javax.swing.JButton();
        AdminForm_RegisterUser = new javax.swing.JButton();
        AdminForm_RegisterPizza = new javax.swing.JButton();
        AdminForm_FinishPizza = new javax.swing.JButton();
        AdminForm_FinishOrder = new javax.swing.JButton();
        AdminForm_Logout = new javax.swing.JButton();
        Pizzaiolo = new javax.swing.JPanel();
        PizzaioloForm_Name = new javax.swing.JLabel();
        PizzaioloForm_Orders = new javax.swing.JScrollPane();
        Orders_Table2 = new javax.swing.JTable();
        PizzaioloForm_FinishPizza = new javax.swing.JButton();
        PizzaioloForm_Logout = new javax.swing.JButton();
        Entregador = new javax.swing.JPanel();
        EntregadorForm_Name = new javax.swing.JLabel();
        EntregadorForm_Orders2 = new javax.swing.JScrollPane();
        Orders_Table3 = new javax.swing.JTable();
        EntregadorForm_FinishOrder = new javax.swing.JButton();
        EntregadorForm_Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainJPanel.setLayout(new java.awt.CardLayout());

        LoginForm_Title.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        LoginForm_Title.setText("Login");

        LoginForm_UsernameLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        LoginForm_UsernameLabel.setText("Usuário");

        LoginForm_UsernameField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        LoginForm_PasswordLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        LoginForm_PasswordLabel.setText("Senha");

        LoginForm_PasswordField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        LoginForm_LoginButton.setText("Login");
        LoginForm_LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginForm_LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginForm_LoginButton)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoginForm_UsernameLabel)
                            .addComponent(LoginForm_PasswordLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginForm_UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoginForm_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LoginForm_Title))
                .addContainerGap(550, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LoginForm_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginForm_UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginForm_UsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginForm_PasswordLabel)
                    .addComponent(LoginForm_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LoginForm_LoginButton)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        MainJPanel.add(Login, "card2");

        AtendenteForm_Name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        AtendenteForm_Name.setText("Atendente: Nome");

        Orders_Table1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Orders_Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Telefone", "Pedido", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AtendenteForm_Orders.setViewportView(Orders_Table1);

        AtendenteForm_OrdersLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        AtendenteForm_OrdersLabel.setText("Pedidos");

        AtendenteForm_Logout.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        AtendenteForm_Logout.setText("Deslogar");
        AtendenteForm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtendenteForm_LogoutActionPerformed(evt);
            }
        });

        AtendenteForm_RegisterOrder.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        AtendenteForm_RegisterOrder.setText("Cadastrar Pedido");
        AtendenteForm_RegisterOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtendenteForm_RegisterOrderActionPerformed(evt);
            }
        });

        AtendenteForm_RegisterClient.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        AtendenteForm_RegisterClient.setText("Cadastrar Cliente");
        AtendenteForm_RegisterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtendenteForm_RegisterClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AtendenteLayout = new javax.swing.GroupLayout(Atendente);
        Atendente.setLayout(AtendenteLayout);
        AtendenteLayout.setHorizontalGroup(
            AtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtendenteLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AtendenteForm_OrdersLabel)
                    .addComponent(AtendenteForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AtendenteLayout.createSequentialGroup()
                        .addComponent(AtendenteForm_RegisterOrder)
                        .addGap(18, 18, 18)
                        .addComponent(AtendenteForm_RegisterClient)
                        .addGap(18, 18, 18)
                        .addComponent(AtendenteForm_Logout))
                    .addComponent(AtendenteForm_Name))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        AtendenteLayout.setVerticalGroup(
            AtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtendenteLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(AtendenteForm_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtendenteForm_RegisterOrder)
                    .addComponent(AtendenteForm_RegisterClient)
                    .addComponent(AtendenteForm_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(AtendenteForm_OrdersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AtendenteForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainJPanel.add(Atendente, "card2");

        AdminForm_Name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        AdminForm_Name.setText("Administrador: Nome");

        Orders_Table.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Orders_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Telefone", "Pedido", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AdminForm_Orders.setViewportView(Orders_Table);

        AdminForm_OrdersLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        AdminForm_OrdersLabel.setText("Pedidos");

        AdminForm_RegisterOrder.setText("Cadastrar Pedido");
        AdminForm_RegisterOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_RegisterOrderActionPerformed(evt);
            }
        });

        AdminForm_RegisterClient.setText("Cadastrar Cliente");
        AdminForm_RegisterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_RegisterClientActionPerformed(evt);
            }
        });

        AdminForm_RegisterUser.setText("Cadastrar Usuario");
        AdminForm_RegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_RegisterUserActionPerformed(evt);
            }
        });

        AdminForm_RegisterPizza.setText("Cadastrar Pizzas");
        AdminForm_RegisterPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_RegisterPizzaActionPerformed(evt);
            }
        });

        AdminForm_FinishPizza.setText("Finalizar Pizza");
        AdminForm_FinishPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_FinishPizzaActionPerformed(evt);
            }
        });

        AdminForm_FinishOrder.setText("Finalizar Entrega");
        AdminForm_FinishOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_FinishOrderActionPerformed(evt);
            }
        });

        AdminForm_Logout.setText("Deslogar");
        AdminForm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminForm_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
        Admin.setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminForm_OrdersLabel)
                    .addComponent(AdminForm_Name)
                    .addComponent(AdminForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdminLayout.createSequentialGroup()
                        .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminForm_RegisterOrder)
                            .addComponent(AdminForm_FinishPizza))
                        .addGap(18, 18, 18)
                        .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminForm_FinishOrder)
                            .addGroup(AdminLayout.createSequentialGroup()
                                .addComponent(AdminForm_RegisterClient)
                                .addGap(18, 18, 18)
                                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AdminForm_Logout)
                                    .addGroup(AdminLayout.createSequentialGroup()
                                        .addComponent(AdminForm_RegisterUser)
                                        .addGap(18, 18, 18)
                                        .addComponent(AdminForm_RegisterPizza)))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(AdminForm_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminForm_RegisterOrder)
                    .addComponent(AdminForm_RegisterClient)
                    .addComponent(AdminForm_RegisterUser)
                    .addComponent(AdminForm_RegisterPizza))
                .addGap(18, 18, 18)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminForm_FinishPizza)
                    .addComponent(AdminForm_FinishOrder)
                    .addComponent(AdminForm_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(AdminForm_OrdersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainJPanel.add(Admin, "card2");

        PizzaioloForm_Name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        PizzaioloForm_Name.setText("Pizzaiolo: Nome");

        Orders_Table2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Orders_Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Telefone", "Pedido", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PizzaioloForm_Orders.setViewportView(Orders_Table2);

        PizzaioloForm_FinishPizza.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        PizzaioloForm_FinishPizza.setText("Finalizar Pizza");
        PizzaioloForm_FinishPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaioloForm_FinishPizzaActionPerformed(evt);
            }
        });

        PizzaioloForm_Logout.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        PizzaioloForm_Logout.setText("Deslogar");
        PizzaioloForm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaioloForm_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PizzaioloLayout = new javax.swing.GroupLayout(Pizzaiolo);
        Pizzaiolo.setLayout(PizzaioloLayout);
        PizzaioloLayout.setHorizontalGroup(
            PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PizzaioloLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PizzaioloLayout.createSequentialGroup()
                        .addComponent(PizzaioloForm_FinishPizza)
                        .addGap(18, 18, 18)
                        .addComponent(PizzaioloForm_Logout))
                    .addComponent(PizzaioloForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PizzaioloForm_Name))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PizzaioloLayout.setVerticalGroup(
            PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PizzaioloLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(PizzaioloForm_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PizzaioloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PizzaioloForm_FinishPizza)
                    .addComponent(PizzaioloForm_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(PizzaioloForm_Orders, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainJPanel.add(Pizzaiolo, "card2");

        EntregadorForm_Name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        EntregadorForm_Name.setText("Entregador: Nome");

        Orders_Table3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Orders_Table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Telefone", "Pedido", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EntregadorForm_Orders2.setViewportView(Orders_Table3);

        EntregadorForm_FinishOrder.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        EntregadorForm_FinishOrder.setText("Finalizar Entrega");
        EntregadorForm_FinishOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntregadorForm_FinishOrderActionPerformed(evt);
            }
        });

        EntregadorForm_Logout.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        EntregadorForm_Logout.setText("Deslogar");
        EntregadorForm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntregadorForm_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EntregadorLayout = new javax.swing.GroupLayout(Entregador);
        Entregador.setLayout(EntregadorLayout);
        EntregadorLayout.setHorizontalGroup(
            EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntregadorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EntregadorLayout.createSequentialGroup()
                        .addComponent(EntregadorForm_FinishOrder)
                        .addGap(18, 18, 18)
                        .addComponent(EntregadorForm_Logout))
                    .addComponent(EntregadorForm_Orders2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntregadorForm_Name))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        EntregadorLayout.setVerticalGroup(
            EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntregadorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(EntregadorForm_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EntregadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntregadorForm_FinishOrder)
                    .addComponent(EntregadorForm_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(EntregadorForm_Orders2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainJPanel.add(Entregador, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void LoginForm_LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:

        if(true) { // sistema de login aqui
            MainJPanel.removeAll();
            MainJPanel.add(Admin);
            MainJPanel.revalidate();
        }

    }                                                     

    private void AtendenteForm_RegisterOrderActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        // TODO add your handling code here:
        this.RegisterOrder();
    }                                                           

    private void AtendenteForm_RegisterClientActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
        this.RegisterClient();
    }                                                            

    private void AtendenteForm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        this.Logout();
    }                                                    

    private void AdminForm_RegisterOrderActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
        this.RegisterOrder();
    }                                                       

    private void AdminForm_RegisterClientActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
        this.RegisterClient();
    }                                                        

    private void AdminForm_RegisterUserActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
        this.RegisterUser();
    }                                                      

    private void AdminForm_RegisterPizzaActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
        this.RegisterPizza();
    }                                                       

    private void AdminForm_FinishPizzaActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        this.FinishPizza();
    }                                                     

    private void AdminForm_FinishOrderActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        this.FinishOrder();
    }                                                     

    private void AdminForm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        this.Logout();
    }                                                

    private void PizzaioloForm_FinishPizzaActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
        this.FinishPizza();
    }                                                         

    private void PizzaioloForm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        this.Logout();
    }                                                    

    private void EntregadorForm_FinishOrderActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
        this.FinishOrder();
    }                                                          

    private void EntregadorForm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        this.Logout();
    }                                                     

    private void RegisterOrder() {
        
    }
    
    private void RegisterClient() {
        
    }
    
    private void RegisterUser() {
        
    }
    
    private void RegisterPizza() {
        
    }
    
    private void FinishPizza() {
        
    }
    
    private void FinishOrder() {
        
    }
    
    private void Logout() {
        
    }
    
    private void Login() {
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Admin;
    private javax.swing.JButton AdminForm_FinishOrder;
    private javax.swing.JButton AdminForm_FinishPizza;
    private javax.swing.JButton AdminForm_Logout;
    private javax.swing.JLabel AdminForm_Name;
    private javax.swing.JScrollPane AdminForm_Orders;
    private javax.swing.JLabel AdminForm_OrdersLabel;
    private javax.swing.JButton AdminForm_RegisterClient;
    private javax.swing.JButton AdminForm_RegisterOrder;
    private javax.swing.JButton AdminForm_RegisterPizza;
    private javax.swing.JButton AdminForm_RegisterUser;
    private javax.swing.JPanel Atendente;
    private javax.swing.JButton AtendenteForm_Logout;
    private javax.swing.JLabel AtendenteForm_Name;
    private javax.swing.JScrollPane AtendenteForm_Orders;
    private javax.swing.JLabel AtendenteForm_OrdersLabel;
    private javax.swing.JButton AtendenteForm_RegisterClient;
    private javax.swing.JButton AtendenteForm_RegisterOrder;
    private javax.swing.JPanel Entregador;
    private javax.swing.JButton EntregadorForm_FinishOrder;
    private javax.swing.JButton EntregadorForm_Logout;
    private javax.swing.JLabel EntregadorForm_Name;
    private javax.swing.JScrollPane EntregadorForm_Orders2;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginForm_LoginButton;
    private javax.swing.JTextField LoginForm_PasswordField;
    private javax.swing.JLabel LoginForm_PasswordLabel;
    private javax.swing.JLabel LoginForm_Title;
    private javax.swing.JTextField LoginForm_UsernameField;
    private javax.swing.JLabel LoginForm_UsernameLabel;
    private javax.swing.JPanel MainJPanel;
    private javax.swing.JTable Orders_Table;
    private javax.swing.JTable Orders_Table1;
    private javax.swing.JTable Orders_Table2;
    private javax.swing.JTable Orders_Table3;
    private javax.swing.JPanel Pizzaiolo;
    private javax.swing.JButton PizzaioloForm_FinishPizza;
    private javax.swing.JButton PizzaioloForm_Logout;
    private javax.swing.JLabel PizzaioloForm_Name;
    private javax.swing.JScrollPane PizzaioloForm_Orders;
    // End of variables declaration                   
}
