Sistema de Pizza: businesslogic.PizzariaTest Class Reference
businesslogic.PizzariaTest Class Reference
Public Member Functions
void setUp ()
void testAddAndFindClient () throws Exception
void testAddRequest () throws Exception
void testCalculatePrice () throws Exception
void testFindOtherProduct () throws Exception
void testFinishing () throws Exception
void testRegisterAndGetOutro () throws Exception
void testRegisterAndGetPizza () throws Exception
void testRegisterEmpAndDoLogin () throws Exception
Detailed Description
Author
Felipe
Definition at line 33 of file PizzariaTest.java.
Member Function Documentation
void businesslogic.PizzariaTest.testAddAndFindClient () throws Exception inline
Test of addClient method, of class Pizzaria.
Definition at line 107 of file PizzariaTest.java.
References businesslogic.Pizzaria.addClient(), businesslogic.Pizzaria.findClient(), pizzasystem.data.Person.getName(), pizzasystem.data.Person.setAddress(), pizzasystem.data.Person.setCep(), pizzasystem.data.Person.setName(), and pizzasystem.data.Person.setPhoneNumber().
void businesslogic.PizzariaTest.testAddRequest () throws Exception inline
Test of addClientRequest method, of class Pizzaria.
Definition at line 129 of file PizzariaTest.java.
References businesslogic.Pizzaria.addClient(), businesslogic.Pizzaria.addRequest(), businesslogic.Pizzaria.getRequests(), pizzasystem.data.Person.setAddress(), pizzasystem.data.Person.setCep(), pizzasystem.data.ClientRequest.setClient(), pizzasystem.data.Person.setName(), pizzasystem.data.Person.setPhoneNumber(), and pizzasystem.data.ClientRequest.setStatus().
void businesslogic.PizzariaTest.testCalculatePrice () throws Exception inline
Test of calculateRequestPrice method, of class Pizzaria.
Definition at line 215 of file PizzariaTest.java.
References businesslogic.Pizzaria.addClient(), pizzasystem.data.ClientRequest.addOther(), pizzasystem.data.ClientRequest.addPizza(), businesslogic.Pizzaria.addRequest(), businesslogic.Pizzaria.calculatePizzaPrice(), businesslogic.Pizzaria.calculateRequestPrice(), businesslogic.Pizzaria.getRequests(), businesslogic.Pizzaria.registerOutro(), businesslogic.Pizzaria.registerPizza(), pizzasystem.data.Person.setAddress(), pizzasystem.data.Person.setCep(), pizzasystem.data.ClientRequest.setClient(), pizzasystem.data.OtherProductType.setName(), pizzasystem.data.PizzaTaste.setName(), pizzasystem.data.Person.setName(), pizzasystem.data.Person.setPhoneNumber(), pizzasystem.data.OtherProductType.setPrice(), pizzasystem.data.PizzaTaste.setPriceBig(), pizzasystem.data.PizzaTaste.setPriceFamily(), pizzasystem.data.PizzaTaste.setPriceMedium(), pizzasystem.data.OtherProduct.setProduct(), pizzasystem.data.Pizza.setSize(), pizzasystem.data.ClientRequest.setStatus(), pizzasystem.data.Pizza.setTaste1(), pizzasystem.data.Pizza.setTaste2(), and pizzasystem.data.Pizza.setTaste3().
void businesslogic.PizzariaTest.testFindOtherProduct () throws Exception inline
Test of findOtherProduct method, of class Pizzaria.
Definition at line 192 of file PizzariaTest.java.
References businesslogic.Pizzaria.findOtherProduct(), businesslogic.Pizzaria.getOtherProductTypes(), pizzasystem.data.OtherProductType.getPrice(), businesslogic.Pizzaria.registerOutro(), pizzasystem.data.OtherProductType.setName(), and pizzasystem.data.OtherProductType.setPrice().
void businesslogic.PizzariaTest.testFinishing () throws Exception inline
Test of finishOrder method, of class Pizzaria.
Definition at line 294 of file PizzariaTest.java.
References businesslogic.Pizzaria.addClient(), businesslogic.Pizzaria.addRequest(), businesslogic.Pizzaria.finishOrder(), businesslogic.Pizzaria.finishPizza(), businesslogic.Pizzaria.getRequests(), pizzasystem.data.Person.setAddress(), pizzasystem.data.Person.setCep(), pizzasystem.data.ClientRequest.setClient(), pizzasystem.data.Person.setName(), pizzasystem.data.Person.setPhoneNumber(), and pizzasystem.data.ClientRequest.setStatus().
void businesslogic.PizzariaTest.testRegisterAndGetOutro () throws Exception inline
Test of registerOutro method, of class Pizzaria.
Definition at line 174 of file PizzariaTest.java.
References businesslogic.Pizzaria.getOtherProductTypes(), businesslogic.Pizzaria.registerOutro(), pizzasystem.data.OtherProductType.setName(), and pizzasystem.data.OtherProductType.setPrice().
void businesslogic.PizzariaTest.testRegisterAndGetPizza () throws Exception inline
Test of registerPizza method, of class Pizzaria.
Definition at line 154 of file PizzariaTest.java.
References businesslogic.Pizzaria.getPizzaTastes(), businesslogic.Pizzaria.registerPizza(), pizzasystem.data.PizzaTaste.setName(), pizzasystem.data.PizzaTaste.setPriceBig(), pizzasystem.data.PizzaTaste.setPriceFamily(), and pizzasystem.data.PizzaTaste.setPriceMedium().
void businesslogic.PizzariaTest.testRegisterEmpAndDoLogin () throws Exception inline
Test of doLogin method, of class Pizzaria.
Definition at line 81 of file PizzariaTest.java.
References pizzasystem.data.Employee.Role.Attendant, businesslogic.Pizzaria.doLogin(), pizzasystem.data.Person.getAddress(), businesslogic.Pizzaria.getCurrentUser(), and businesslogic.Pizzaria.registerEmployee().
The documentation for this class was generated from the following file:
test/businesslogic/PizzariaTest.java