Sistema de Pizza: pizzasystem.transfer.PersonDAO Class Reference
pizzasystem.transfer.PersonDAO Class Reference
Public Member Functions
PersonDAO (Person object)
Person getObject ()
void save (Connection db) throws SQLException
Static Public Member Functions
static Person fetch (Connection db, String phoneNumber) throws SQLException
Static Protected Member Functions
static void setFromResultSet (ResultSet result, Person object) throws SQLException
Detailed Description
Definition at line 14 of file PersonDAO.java.
Member Function Documentation
static Person pizzasystem.transfer.PersonDAO.fetch (Connection db, String phoneNumber) throws SQLException inline static
Parameters
db
phoneNumber
Returns
retorna a lista de pessoa que esta no database
Exceptions
SQLException
Definition at line 45 of file PersonDAO.java.
References pizzasystem.transfer.PersonDAO.setFromResultSet().
Referenced by businesslogic.Pizzaria.findClient().
void pizzasystem.transfer.PersonDAO.save (Connection db) throws SQLException inline
Parameters
db
Exceptions
SQLException
Definition at line 63 of file PersonDAO.java.
Referenced by businesslogic.Pizzaria.addClient(), and pizzasystem.transfer.EmployeeDAO.save().
static void pizzasystem.transfer.PersonDAO.setFromResultSet (ResultSet result, Person object) throws SQLException inline static protected
Parameters
result
Exceptions
SQLException
Definition at line 31 of file PersonDAO.java.
Referenced by pizzasystem.transfer.PersonDAO.fetch(), pizzasystem.transfer.EmployeeDAO.setFromResultSet(), and pizzasystem.transfer.ClientRequestDAO.setFromResultSet().
The documentation for this class was generated from the following file:
src/pizzasystem/transfer/PersonDAO.java