Sistema de Pizza: pizzasystem.transfer.ClientRequestDAO Class Reference
pizzasystem.transfer.ClientRequestDAO Class Reference
Public Member Functions
ClientRequestDAO (ClientRequest object)
void deleteRequests (Connection db) throws SQLException
ClientRequest getObject ()
void save (Connection db) throws SQLException
Static Public Member Functions
static List< ClientRequest > fetchAll (Connection db) throws SQLException
Static Protected Member Functions
static void fillOthers (Connection db, List< ClientRequest > requests) throws SQLException
static void fillPizzas (Connection db, List< ClientRequest > requests) throws SQLException
static void setFromResultSet (ResultSet result, ClientRequest object) throws SQLException
Detailed Description
Definition at line 16 of file ClientRequestDAO.java.
Member Function Documentation
static List<ClientRequest> pizzasystem.transfer.ClientRequestDAO.fetchAll (Connection db) throws SQLException inline static
Parameters
db
Returns
Retorna a lista de pedidos que esta no database
Exceptions
SQLException
Definition at line 142 of file ClientRequestDAO.java.
References pizzasystem.transfer.ClientRequestDAO.fillOthers(), pizzasystem.transfer.ClientRequestDAO.fillPizzas(), and pizzasystem.transfer.ClientRequestDAO.setFromResultSet().
Referenced by businesslogic.Pizzaria.getRequests().
static void pizzasystem.transfer.ClientRequestDAO.fillOthers (Connection db, List< ClientRequest > requests) throws SQLException inline static protected
Parameters
db
requests
Exceptions
SQLException
Definition at line 95 of file ClientRequestDAO.java.
References pizzasystem.data.ClientRequest.getOthers(), and pizzasystem.transfer.OtherProductDAO.setFromResultSet().
Referenced by pizzasystem.transfer.ClientRequestDAO.fetchAll().
static void pizzasystem.transfer.ClientRequestDAO.fillPizzas (Connection db, List< ClientRequest > requests) throws SQLException inline static protected
Parameters
db
requests
Exceptions
SQLException
Definition at line 48 of file ClientRequestDAO.java.
References pizzasystem.data.ClientRequest.getPizzas(), and pizzasystem.transfer.PizzaDAO.setFromResultSet().
Referenced by pizzasystem.transfer.ClientRequestDAO.fetchAll().
void pizzasystem.transfer.ClientRequestDAO.save (Connection db) throws SQLException inline
Parameters
db
Exceptions
SQLException
Definition at line 228 of file ClientRequestDAO.java.
Referenced by businesslogic.Pizzaria.addRequest(), businesslogic.Pizzaria.finishOrder(), and businesslogic.Pizzaria.finishPizza().
static void pizzasystem.transfer.ClientRequestDAO.setFromResultSet (ResultSet result, ClientRequest object) throws SQLException inline static protected
Parameters
result
Exceptions
SQLException
Definition at line 34 of file ClientRequestDAO.java.
References pizzasystem.transfer.PersonDAO.setFromResultSet().
Referenced by pizzasystem.transfer.ClientRequestDAO.fetchAll().
The documentation for this class was generated from the following file:
src/pizzasystem/transfer/ClientRequestDAO.java