Sistema de Pizza: pizzasystem.data.Person Class Reference
pizzasystem.data.Person Class Reference
Public Member Functions
String getAddress ()
String getCep ()
String getName ()
String getPhoneNumber ()
void setAddress (String address)
void setCep (String cep)
void setName (String name)
void setPhoneNumber (String phoneNumber)
Detailed Description
Definition at line 7 of file Person.java.
Member Function Documentation
String pizzasystem.data.Person.getAddress () inline
Returns
retorna o endereço da pessoa
Definition at line 65 of file Person.java.
Referenced by businesslogic.PizzariaTest.testRegisterEmpAndDoLogin().
String pizzasystem.data.Person.getCep () inline
Returns
retorna o cep da pessoa
Definition at line 33 of file Person.java.
String pizzasystem.data.Person.getName () inline
Returns
retorna o nome da pessoa
Definition at line 49 of file Person.java.
Referenced by businesslogic.PizzariaTest.testAddAndFindClient().
String pizzasystem.data.Person.getPhoneNumber () inline
Returns
o numero de telefone da pessoa
Definition at line 17 of file Person.java.
void pizzasystem.data.Person.setAddress (String address) inline
Parameters
address
Definition at line 73 of file Person.java.
Referenced by businesslogic.PizzariaTest.testAddAndFindClient(), businesslogic.PizzariaTest.testAddRequest(), businesslogic.PizzariaTest.testCalculatePrice(), and businesslogic.PizzariaTest.testFinishing().
void pizzasystem.data.Person.setCep (String cep) inline
Parameters
cep
Definition at line 41 of file Person.java.
Referenced by businesslogic.PizzariaTest.testAddAndFindClient(), businesslogic.PizzariaTest.testAddRequest(), businesslogic.PizzariaTest.testCalculatePrice(), and businesslogic.PizzariaTest.testFinishing().
void pizzasystem.data.Person.setName (String name) inline
Parameters
name
Definition at line 57 of file Person.java.
Referenced by businesslogic.PizzariaTest.testAddAndFindClient(), businesslogic.PizzariaTest.testAddRequest(), businesslogic.PizzariaTest.testCalculatePrice(), and businesslogic.PizzariaTest.testFinishing().
void pizzasystem.data.Person.setPhoneNumber (String phoneNumber) inline
Parameters
phoneNumber
Definition at line 25 of file Person.java.
Referenced by businesslogic.PizzariaTest.testAddAndFindClient(), businesslogic.PizzariaTest.testAddRequest(), businesslogic.PizzariaTest.testCalculatePrice(), and businesslogic.PizzariaTest.testFinishing().
The documentation for this class was generated from the following file:
src/pizzasystem/data/Person.java