Sistema de Pizza: pizzasystem.transfer.PizzaTasteDAO Class Reference
pizzasystem.transfer.PizzaTasteDAO Class Reference
Public Member Functions
PizzaTasteDAO (PizzaTaste object)
PizzaTaste getObject ()
void save (Connection db) throws SQLException
Static Public Member Functions
static List< PizzaTaste > fetchAll (Connection db) throws SQLException
Static Protected Member Functions
static void setFromResultSet (ResultSet result, PizzaTaste object) throws SQLException
Detailed Description
Definition at line 17 of file PizzaTasteDAO.java.
Member Function Documentation
static List<PizzaTaste> pizzasystem.transfer.PizzaTasteDAO.fetchAll (Connection db) throws SQLException inline static
Parameters
db
Returns
retorna a lista de todas as pizzas que estão no database
Exceptions
SQLException
Definition at line 47 of file PizzaTasteDAO.java.
References pizzasystem.transfer.PizzaTasteDAO.setFromResultSet().
Referenced by businesslogic.Pizzaria.getPizzaTastes().
void pizzasystem.transfer.PizzaTasteDAO.save (Connection db) throws SQLException inline
Parameters
db
Exceptions
SQLException
Definition at line 67 of file PizzaTasteDAO.java.
Referenced by businesslogic.Pizzaria.registerPizza().
static void pizzasystem.transfer.PizzaTasteDAO.setFromResultSet (ResultSet result, PizzaTaste object) throws SQLException inline static protected
Parameters
result
Exceptions
SQLException
Definition at line 34 of file PizzaTasteDAO.java.
Referenced by pizzasystem.transfer.PizzaTasteDAO.fetchAll().
The documentation for this class was generated from the following file:
src/pizzasystem/transfer/PizzaTasteDAO.java