Sistema de Pizza: pizzasystem.transfer.OtherProductTypeDAO Class Reference
pizzasystem.transfer.OtherProductTypeDAO Class Reference
Public Member Functions
OtherProductTypeDAO (OtherProductType object)
OtherProductType getObject ()
void save (Connection db) throws SQLException
Static Public Member Functions
static List< OtherProductType > fetchAll (Connection db) throws SQLException
Static Protected Member Functions
static void setFromResultSet (ResultSet result, OtherProductType object) throws SQLException
Detailed Description
Definition at line 16 of file OtherProductTypeDAO.java.
Member Function Documentation
static List<OtherProductType> pizzasystem.transfer.OtherProductTypeDAO.fetchAll (Connection db) throws SQLException inline static
Parameters
db
Returns
Retorna a lista com todos os produtos disponiveis do database
Exceptions
SQLException
Definition at line 44 of file OtherProductTypeDAO.java.
References pizzasystem.transfer.OtherProductTypeDAO.setFromResultSet().
Referenced by businesslogic.Pizzaria.getOtherProductTypes().
void pizzasystem.transfer.OtherProductTypeDAO.save (Connection db) throws SQLException inline
Parameters
db
Exceptions
SQLException
Definition at line 64 of file OtherProductTypeDAO.java.
Referenced by businesslogic.Pizzaria.registerOutro().
static void pizzasystem.transfer.OtherProductTypeDAO.setFromResultSet (ResultSet result, OtherProductType object) throws SQLException inline static protected
Parameters
result
Exceptions
SQLException
Definition at line 33 of file OtherProductTypeDAO.java.
Referenced by pizzasystem.transfer.OtherProductTypeDAO.fetchAll().
The documentation for this class was generated from the following file:
src/pizzasystem/transfer/OtherProductTypeDAO.java