Sistema de Pizza: pizzasystem.ui.MainFrame Class Reference
pizzasystem.ui.MainFrame Class Reference
Static Public Member Functions
static String[] getDrinkList ()
static String[] getTasteList ()
static void main (String args[])
Detailed Description
Author
jools
Definition at line 37 of file MainFrame.java.
Member Function Documentation
static String [] pizzasystem.ui.MainFrame.getDrinkList () inline static
Returns
a lista de outros produtos em formato de array
Definition at line 61 of file MainFrame.java.
References businesslogic.Pizzaria.getOtherProductTypes(), and pizzasystem.Main.getPizzaria().
static String [] pizzasystem.ui.MainFrame.getTasteList () inline static
Returns
a lista de sabores em formato de array
Definition at line 45 of file MainFrame.java.
References pizzasystem.Main.getPizzaria(), and businesslogic.Pizzaria.getPizzaTastes().
static void pizzasystem.ui.MainFrame.main (String args[]) inline static
Parameters
args the command line arguments
Definition at line 1563 of file MainFrame.java.
The documentation for this class was generated from the following file:
src/pizzasystem/ui/MainFrame.java