Sistema de Pizza: businesslogic.Pizzaria Class Reference
businesslogic.Pizzaria Class Reference
Public Member Functions
void addClient (Person client) throws SQLException
void addRequest (ClientRequest request) throws SQLException
Float calculatePizzaPrice (Pizza pizza) throws SQLException
Float calculateRequestPrice (ClientRequest request) throws SQLException
int doLogin (String user, String pass) throws SQLException
Person findClient (String phoneNumber) throws SQLException
OtherProductType findOtherProduct (String otherName) throws SQLException
void finishOrder () throws SQLException
void finishPizza () throws SQLException
Employee getCurrentUser ()
List< OtherProductType > getOtherProductTypes () throws SQLException
List< PizzaTaste > getPizzaTastes () throws SQLException
List< ClientRequest > getRequests () throws SQLException
void logOut ()
void registerEmployee (Employee employee) throws SQLException
void registerOutro (OtherProductType outro) throws SQLException
void registerPizza (PizzaTaste pizza) throws SQLException
void removeDelivered () throws SQLException
Protected Member Functions
Connection getDb () throws SQLException
Protected Attributes
Connection db
Detailed Description
Author
Gabe
Definition at line 29 of file Pizzaria.java.
Member Function Documentation
void businesslogic.Pizzaria.addClient (Person client) throws SQLException inline
Parameters
client
Exceptions
SQLException
Definition at line 93 of file Pizzaria.java.
References pizzasystem.transfer.PersonDAO.save().
void businesslogic.Pizzaria.addRequest (ClientRequest request) throws SQLException inline
Parameters
request
Exceptions
SQLException
Definition at line 223 of file Pizzaria.java.
References pizzasystem.transfer.ClientRequestDAO.save().
Float businesslogic.Pizzaria.calculatePizzaPrice (Pizza pizza) throws SQLException inline
Parameters
pizza
Returns
Retorna o valor da pizza baseado nos 3 sabores pedidos, o valor da pizza será o maior valor entre as pedidas
Exceptions
SQLException
Definition at line 263 of file Pizzaria.java.
References businesslogic.Pizzaria.getPizzaTastes().
Float businesslogic.Pizzaria.calculateRequestPrice (ClientRequest request) throws SQLException inline
Parameters
request
Returns
Retorna o valor total do pedido baseado em todas as pizzas e nos outros produtos
Exceptions
SQLException
Definition at line 237 of file Pizzaria.java.
References businesslogic.Pizzaria.getOtherProductTypes(), and businesslogic.Pizzaria.getPizzaTastes().
int businesslogic.Pizzaria.doLogin (String user, String pass) throws SQLException inline
Parameters
user
pass
Returns
Faz login com o usuario e password fornecidos e retorna um inteiro representando que tipo de funcionario fez login
Exceptions
SQLException
Definition at line 57 of file Pizzaria.java.
References pizzasystem.transfer.EmployeeDAO.fetch(), businesslogic.Pizzaria.getCurrentUser(), pizzasystem.data.Employee.getHashPass(), pizzasystem.data.Employee.getRole(), and pizzasystem.utility.PasswordHasher.hash().
Person businesslogic.Pizzaria.findClient (String phoneNumber) throws SQLException inline
Parameters
phoneNumber
Returns
Retorna o cliente que tem o numero de telefone passado como argumento
Exceptions
SQLException
Definition at line 114 of file Pizzaria.java.
References pizzasystem.transfer.PersonDAO.fetch().
OtherProductType businesslogic.Pizzaria.findOtherProduct (String otherName) throws SQLException inline
Parameters
otherName
Returns
retorna o produto que tem o nome passado como argumento
Exceptions
SQLException
Definition at line 201 of file Pizzaria.java.
References businesslogic.Pizzaria.getOtherProductTypes().
void businesslogic.Pizzaria.finishOrder () throws SQLException inline
Exceptions
SQLException
Definition at line 309 of file Pizzaria.java.
References businesslogic.Pizzaria.getRequests(), and pizzasystem.transfer.ClientRequestDAO.save().
void businesslogic.Pizzaria.finishPizza () throws SQLException inline
Exceptions
SQLException
Definition at line 324 of file Pizzaria.java.
References businesslogic.Pizzaria.getRequests(), and pizzasystem.transfer.ClientRequestDAO.save().
Employee businesslogic.Pizzaria.getCurrentUser () inline
Returns
the currentUser
Definition at line 191 of file Pizzaria.java.
Referenced by businesslogic.Pizzaria.doLogin().
List<OtherProductType> businesslogic.Pizzaria.getOtherProductTypes () throws SQLException inline
Returns
retorna a lista de outros produtos disponiveis que estão no database
Exceptions
SQLException
Definition at line 184 of file Pizzaria.java.
References pizzasystem.transfer.OtherProductTypeDAO.fetchAll().
Referenced by businesslogic.Pizzaria.calculateRequestPrice(), businesslogic.Pizzaria.findOtherProduct(), and pizzasystem.ui.MainFrame.getDrinkList().
List<PizzaTaste> businesslogic.Pizzaria.getPizzaTastes () throws SQLException inline
Returns
retorna a lista de pizzas disponiveis que estão no database
Exceptions
SQLException
Definition at line 175 of file Pizzaria.java.
References pizzasystem.transfer.PizzaTasteDAO.fetchAll().
Referenced by businesslogic.Pizzaria.calculatePizzaPrice(), businesslogic.Pizzaria.calculateRequestPrice(), and pizzasystem.ui.MainFrame.getTasteList().
List<ClientRequest> businesslogic.Pizzaria.getRequests () throws SQLException inline
Returns
the requests
Exceptions
java.sql.SQLException
Definition at line 214 of file Pizzaria.java.
References pizzasystem.transfer.ClientRequestDAO.fetchAll().
Referenced by businesslogic.Pizzaria.finishOrder(), and businesslogic.Pizzaria.finishPizza().
void businesslogic.Pizzaria.registerEmployee (Employee employee) throws SQLException inline
Parameters
employee
Exceptions
SQLException
Definition at line 149 of file Pizzaria.java.
References pizzasystem.transfer.EmployeeDAO.save().
void businesslogic.Pizzaria.registerOutro (OtherProductType outro) throws SQLException inline
Parameters
outro
Exceptions
SQLException
Definition at line 139 of file Pizzaria.java.
References pizzasystem.transfer.OtherProductTypeDAO.save().
void businesslogic.Pizzaria.registerPizza (PizzaTaste pizza) throws SQLException inline
Parameters
pizza
Exceptions
SQLException
Definition at line 129 of file Pizzaria.java.
References pizzasystem.transfer.PizzaTasteDAO.save().
The documentation for this class was generated from the following file:
src/businesslogic/Pizzaria.java