Sistema de Pizza: pizzasystem.transfer.EmployeeDAO Class Reference
pizzasystem.transfer.EmployeeDAO Class Reference
Public Member Functions
EmployeeDAO (Employee object)
Employee getObject ()
void save (Connection db) throws SQLException
Static Public Member Functions
static Employee fetch (Connection db, String user) throws SQLException
Static Protected Member Functions
static void setFromResultSet (ResultSet result, Employee object) throws SQLException
Detailed Description
Definition at line 14 of file EmployeeDAO.java.
Member Function Documentation
static Employee pizzasystem.transfer.EmployeeDAO.fetch (Connection db, String user) throws SQLException inline static
Parameters
db
user
Returns
Retorna todos os funcionarios que estão no database
Exceptions
SQLException
Definition at line 45 of file EmployeeDAO.java.
References pizzasystem.transfer.EmployeeDAO.setFromResultSet().
Referenced by businesslogic.Pizzaria.doLogin().
void pizzasystem.transfer.EmployeeDAO.save (Connection db) throws SQLException inline
Parameters
db
Exceptions
SQLException
Definition at line 64 of file EmployeeDAO.java.
References pizzasystem.transfer.PersonDAO.save().
Referenced by businesslogic.Pizzaria.registerEmployee().
static void pizzasystem.transfer.EmployeeDAO.setFromResultSet (ResultSet result, Employee object) throws SQLException inline static protected
Parameters
result
Exceptions
SQLException
Definition at line 31 of file EmployeeDAO.java.
References pizzasystem.transfer.PersonDAO.setFromResultSet().
Referenced by pizzasystem.transfer.EmployeeDAO.fetch().
The documentation for this class was generated from the following file:
src/pizzasystem/transfer/EmployeeDAO.java